package vistas;

import clases.Rol;
import clases.Usuario;
import controlador.rolController;
import controlador.usuarioController;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.*;
import util.Iconos;

/**
 *
 * @author Administrador
 */
public class frmNuevoUsuario extends JInternalFrame {

    private usuarioController controlador; // <--- variable global

    /**
     * Creates new form FrnUsuario
     */
    public frmNuevoUsuario() {
        initComponents();
        Iconos();
        cargarRoles();
        Limpiar();

        this.controlador = usuarioController.getInstance(); // Singleton

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setClosable(true);      // Mostrar botón de cerrar
        setIconifiable(false);  // Ocultar minimizar
        setMaximizable(false);  // Ocultar maximizar
        setResizable(false);    // Desactivar redimensionar
        this.setTitle("Mantenimiento");
        modoRegistroNuevo();

    }

    private void Iconos() {
        // Asignar iconos  
        btnRegistrar.setIcon(Iconos.get("guardar-datos.png"));
        btnCancelar.setIcon(Iconos.get("cancelar.png"));
    }

    private void Limpiar() {
        txtNombreUsuario.setText("");
        cboRoles.setSelectedIndex(0);
        txtCorreo.setText("");
        txtContraseña.setText("");
        chkEstado.setSelected(false);

        txtRolId.setVisible(false);

    }

    private JTable tablaUsuarios; // referencia al JTable del formulario principal
    private boolean estadoUsuario;

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        cboRoles = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        chkEstado = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        txtRolId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre ");

        jLabel2.setText("Rol");

        jLabel3.setText("Correo");

        jLabel4.setText("Contraseña");

        txtNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreUsuarioKeyTyped(evt);
            }
        });

        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });

        cboRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRolesActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("REGISTRO DE USUARIO");

        btnCancelar.setBackground(new java.awt.Color(244, 67, 54));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(76, 175, 80));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar-datos.png"))); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(78, 78, 78)
                                .addComponent(chkEstado))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cboRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRolId, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addGap(125, 125, 125)
                                .addComponent(btnCancelar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(54, 54, 54)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRolId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(chkEstado))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Método para asignarla desde fuera
    public void setTablaUsuarios(JTable tabla) {
        this.tablaUsuarios = tabla;
    }
    private boolean modoEdicion = false;
    private int idUsuarioEditar = -1;

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        new frmDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void modoRegistroNuevo() {

        chkEstado.setSelected(true);         // Activo por defecto
        chkEstado.setEnabled(false);         // No se puede modificar
    }

    private void cargarRoles() {
        rolController controller = new rolController();
        List<Rol> roles = controller.obtenerRoles();

        cboRoles.removeAllItems();
        for (Rol r : roles) {
            cboRoles.addItem(r);
        }
    }

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (controlador == null) {
            controlador = usuarioController.getInstance();
        }

        // Relacionar variables de la GUI  
        String nombre = txtNombreUsuario.getText().trim();
        String rol = cboRoles.getSelectedItem() != null ? cboRoles.getSelectedItem().toString() : "";
        String correo = txtCorreo.getText().trim();
        String password = new String(txtContraseña.getPassword());
        boolean estado = chkEstado.isSelected();

        // --- Validar rol seleccionado ---
        Rol rolSeleccionado = (Rol) cboRoles.getSelectedItem();
        if (rolSeleccionado == null || rolSeleccionado.getIdRol() == 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un rol válido.");
            return;
        }
        // ID y nombre del rol
        int idRol = rolSeleccionado.getIdRol();
        String rolNombre = rolSeleccionado.getNombreRol();
        txtRolId.setText(String.valueOf(idRol));

        // Crear objeto Usuario
        Usuario u = new Usuario();
        u.setNombre(nombre);
        u.setIdRol(idRol); // ID para SP
        u.setRol(rolNombre); // Rol_Usuario para SP
        u.setCorreo(correo);
        u.setContrasena(password);
        u.setEstado(estado);

        boolean exito;

        if (modoEdicion) {
            // 🔹 MODO EDICIÓN
            u.setId(idUsuarioEditar);

            // Si la contraseña es la de marcador (no se modificó)
            if (password.equals("**********") || password.isBlank()) {
                u.setContrasena(null); // ⚡ no cambiar contraseña
            }
            exito = controlador.actualizarUsuario(u);
        } else {
            // 🔹 MODO REGISTRO
            if (nombre.isEmpty() || correo.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "️ Todos los campos son obligatorios.");
                return;
            }
            exito = controlador.registrarUsuario(u);
        }
        // Mostrar mensaje según tipo
        switch (controlador.getTipoMensaje()) {
            case 0: // ERROR
                JOptionPane.showMessageDialog(this, controlador.getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case 1: // ADVERTENCIA
                JOptionPane.showMessageDialog(this, controlador.getMensaje(), "Advertencia", JOptionPane.WARNING_MESSAGE);
                break;
            case 2: // ÉXITO
                JOptionPane.showMessageDialog(this, controlador.getMensaje(), "Éxito", JOptionPane.INFORMATION_MESSAGE);
                if (!modoEdicion) {
                    Limpiar(); // limpiar solo al registrar
                }
                if (modoEdicion && exito) {
                    dispose(); // cerrar al actualizar
                }
                break;
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        char c = evt.getKeyChar();
        String texto = txtCorreo.getText();

        // Permitir letras, números, punto, guion, guion bajo y @
        if (!Character.isLetterOrDigit(c) && c != '.' && c != '-' && c != '_' && c != '@' && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume(); // Ignorar el carácter
        }

        // Permitir solo un @
        if (c == '@' && texto.contains("@")) {
            evt.consume();
        }

        // Opcional: limitar la longitud máxima del correo (ej. 50 caracteres)
        if (texto.length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void txtNombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUsuarioKeyTyped
        char c = evt.getKeyChar();

        // Permitir solo letras y espacios
        if (!Character.isLetter(c) && c != ' ' && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume(); // Ignora el carácter si no es válido
        }

        // Opcional: limitar la longitud máxima (ej. 50 caracteres)
        if (txtNombreUsuario.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreUsuarioKeyTyped

    private void seleccionarRol(int id) {
        for (int i = 0; i < cboRoles.getItemCount(); i++) {
            Rol r = cboRoles.getItemAt(i);
            if (r.getIdRol() == id) {
                cboRoles.setSelectedIndex(i);
                break;
            }
        }
    }

    private void cboRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRolesActionPerformed
        Rol rol = (Rol) cboRoles.getSelectedItem();
        if (rol != null) {
            txtRolId.setText(String.valueOf(rol.getIdRol()));
        } else {
            txtRolId.setText(""); // limpiar si no hay selección
        }
    }//GEN-LAST:event_cboRolesActionPerformed

    // 🔹 Carga los datos del usuario en los campos del formulario
    public void cargarDatosParaEditar(Usuario u) {
        if (u == null) {
            JOptionPane.showMessageDialog(this, "No se han recibido datos para editar.");
            return;
        }

        // Guarda el ID del usuario en la variable global
        this.idUsuarioEditar = u.getId();

        // Cambia a modo edición
        this.modoEdicion = true;

        // Cambia el título del formulario (opcional)
        this.setTitle("Editar Usuario");

        // Rellena los campos con los datos del usuario
        txtNombreUsuario.setText(u.getNombre());
        cboRoles.setSelectedItem(u.getRol());
        txtCorreo.setText(u.getCorreo());
        // Contraseña: marcador
        txtContraseña.setText("**********");

        // 🔹 Reflejar el estado booleano en el JCheckBox
        chkEstado.setSelected(u.isEstado());

        chkEstado.setEnabled(true); // Solo editable al editar

        // 🔹 Seleccionar el Rol correcto en el combo
        for (int i = 0; i < cboRoles.getItemCount(); i++) {
            Rol rolItem = (Rol) cboRoles.getItemAt(i);
            if (rolItem.getIdRol() == u.getIdRol()) {
                cboRoles.setSelectedIndex(i);
                break;
            }
        }

        // Cambiar el texto del botón para indicar que ahora es edición
        btnRegistrar.setText("ACTUALIZAR");
    }

    /**
     * @param args the command line arguments
     */
    public void setModoEdicion(boolean modo) {
        this.modoEdicion = modo;
    }

    public void setIdUsuarioEditar(int id) {
        this.idUsuarioEditar = id;
    }

    public boolean isEstadoUsuario() {
        return estadoUsuario;
    }

    public void setEstadoUsuario(boolean estadoUsuario) {
        this.estadoUsuario = estadoUsuario;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNuevoUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNuevoUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNuevoUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNuevoUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNuevoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<Rol> cboRoles;
    private javax.swing.JCheckBox chkEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtRolId;
    // End of variables declaration//GEN-END:variables
}
