package vistas;

import clases.Administrador;
import clases.Area;
import clases.SesionUsuario;
import clases.Trabajador;
import clases.Turno;
import clases.Usuario;
import controlador.areaController;
import controlador.trabajadorController;
import controlador.turnoController;
import java.beans.PropertyVetoException;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import vistas.frmDashboard;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingUtilities;
import util.Iconos;

/**
 *
 * @author v1ct0
 */
public class frmNuevoTrabajador extends JInternalFrame {

    /**
     * Creates new form NuevoTrabajadorForm
     */
    private Usuario usuarioActual;

    public frmNuevoTrabajador() {
        initComponents();
        this.usuarioActual = SesionUsuario.getUsuarioActual(); // 🔹 recupera usuario en sesión
        habilitarCampos();
        cargarAreas();  // 🔹 Carga las áreas al iniciar
        cargarTurnos();
        aplicarPermisosTrabajador();
        // Tamaño y centrado
        this.setSize(950, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setClosable(true);      // Mostrar botón de cerrar
        setIconifiable(false);  // Ocultar minimizar
        setMaximizable(false);  // Ocultar maximizar
        setResizable(false);    // Desactivar redimensionar
        this.setTitle("Registro Trabajador");
        Ocultar();
        Limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtEspecialidad = new javax.swing.JTextField();
        btnVolverDashboard = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        cboArea = new javax.swing.JComboBox<>();
        cboHorario = new javax.swing.JComboBox<>();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chkEstado = new javax.swing.JCheckBox();
        lblImagen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("Especialidad:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setText("Horario");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("REGISTRO DE NUEVO TRABAJADOR");

        btnRegistrar.setBackground(new java.awt.Color(76, 175, 80));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar-datos.png"))); // NOI18N
        btnRegistrar.setText("GUARDAR");
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(244, 67, 54));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidadActionPerformed(evt);
            }
        });

        btnVolverDashboard.setBackground(new java.awt.Color(240, 240, 240));
        btnVolverDashboard.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVolverDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datos.png"))); // NOI18N
        btnVolverDashboard.setText("Dashboard");
        btnVolverDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverDashboardActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setText("Apellido:");

        lblArea.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblArea.setText("Area:");

        cboArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAreaActionPerformed(evt);
            }
        });

        cboHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHorarioActionPerformed(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblCodigo.setText("Codigo:");

        txtCodigo.setEditable(false);

        txtHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorarioActionPerformed(evt);
            }
        });

        txtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setText("Estado:");

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-home-salon-100.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnVolverDashboard)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtApellido)
                                        .addComponent(txtNombre)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(chkEstado))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(lblImagen))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnVolverDashboard)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private areaController areaController = new areaController();
    private turnoController turnoController = new turnoController();

    private boolean modoEdicion = false;
    private int idTrabajadorEditar = -1;
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        new frmDashboard().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void Iconos() {
        // Asignar iconos  
        lblImagen.setIcon(Iconos.get("icons8-home-salon-100.png"));
        btnRegistrar.setIcon(Iconos.get("guardar-datos.png"));
        btnCancelar.setIcon(Iconos.get("cancelar.png"));
        btnVolverDashboard.setIcon(Iconos.get("datos.png"));
    }

    public void habilitarCampos() {
        txtNombre.setEnabled(true);
        txtApellido.setEnabled(true);
        txtHorario.setEnabled(true);
        txtArea.setEnabled(true);
        cboArea.setEnabled(true);
        txtHorario.setEnabled(true);
        cboHorario.setEnabled(true);
        chkEstado.setEnabled(true);

        btnRegistrar.setText("REGISTRAR");
        this.modoEdicion = false;
        this.idTrabajadorEditar = 0;
    }


    private void txtEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidadActionPerformed

    private void Ocultar() {
        // 🔹 Ocultar label y campo de código
        lblCodigo.setVisible(false);
        txtCodigo.setVisible(false);
        txtHorario.setVisible(false);
        txtArea.setVisible(false);

        // 🔹 Bloquear (por si lo muestras luego)
        txtCodigo.setEditable(false);
        txtHorario.setEditable(false);
        txtArea.setEditable(false);
    }

    private void Limpiar() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtEspecialidad.setText("");
        cboHorario.setSelectedIndex(0);
        txtHorario.setText("");
        cboArea.setSelectedIndex(0);
        txtArea.setText("");
        chkEstado.setSelected(true);
    }

    public void configurarModoFormulario(boolean esEdicion) {
        if (esEdicion) {
            lblCodigo.setVisible(true);
            txtCodigo.setVisible(true);
            txtCodigo.setEditable(false);
            btnRegistrar.setText("ACTUALIZAR");
        } else {
            lblCodigo.setVisible(false);
            txtCodigo.setVisible(false);
            txtCodigo.setEditable(false);
            btnRegistrar.setText("GUARDAR");
            Limpiar();
        }
    }

    public void aplicarPermisosTrabajador() {
        if (usuarioActual instanceof Administrador) {
            Administrador admin = (Administrador) usuarioActual;

            // Campos siempre editables
            txtNombre.setEnabled(true);
            txtApellido.setEnabled(true);
            txtEspecialidad.setEnabled(true);
            txtArea.setEnabled(true);
            txtHorario.setEnabled(true);

            // Estado editable solo para Administrador Completo
            chkEstado.setEnabled(admin.getTipo() == Administrador.Tipo.Completo);

        } else if ("Recepcionista".equalsIgnoreCase(usuarioActual.getRol())) {
            txtNombre.setEnabled(true);
            txtApellido.setEnabled(true);
            txtEspecialidad.setEnabled(true);
            txtArea.setEnabled(true);
            txtHorario.setEnabled(true);

            chkEstado.setEnabled(false); // no editable

        } else {
            txtNombre.setEnabled(false);
            txtApellido.setEnabled(false);
            txtEspecialidad.setEnabled(false);
            txtArea.setEnabled(false);
            txtHorario.setEnabled(false);
            chkEstado.setEnabled(false);
        }

        // Para todos los roles: si no puede editar el estado, mostrarlo como activo por defecto
        if (!chkEstado.isEnabled()) {
            chkEstado.setSelected(true);
        }
    }

    private void cargarAreas() {
        areaController controller = new areaController();
        List<Area> lista = controller.obtenerAreas();

        cboArea.removeAllItems();
        cboArea.addItem(new Area(0, "----Seleccione un área----"));
        for (Area a : lista) {
            cboArea.addItem(a);
        }
    }

    private void cargarTurnos() {
        turnoController controller = new turnoController();
        List<Turno> lista = controller.obtenerTurnos();

        cboHorario.removeAllItems();
        cboHorario.addItem(new Turno(0, "----Seleccione un turno----", "", ""));
        for (Turno t : lista) {
            cboHorario.addItem(t);
        }
    }

    // 🔹 Selecciona el área en el combo según ID (int) o nombre (String)
    private void seleccionarArea(String valor) {
        if (valor == null || valor.isEmpty()) {
            return;
        }

        for (int i = 0; i < cboArea.getItemCount(); i++) {
            Area a = (Area) cboArea.getItemAt(i);

            // 🔸 Si el valor es numérico, comparamos por ID
            if (valor.matches("\\d+") && a.getIdArea() == Integer.parseInt(valor)) {
                cboArea.setSelectedIndex(i);
                return;
            }

            // 🔸 Si no es numérico, comparamos por nombre
            if (a.getNombreArea().equalsIgnoreCase(valor)) {
                cboArea.setSelectedIndex(i);
                return;
            }
        }
    }

    // 🔹 Selecciona el turno en el combo según ID o nombre
    private void seleccionarTurno(String valor) {
        if (valor == null || valor.isEmpty()) {
            return;
        }

        for (int i = 0; i < cboHorario.getItemCount(); i++) {
            Turno t = (Turno) cboHorario.getItemAt(i);

            if (valor.matches("\\d+") && t.getIdTurno() == Integer.parseInt(valor)) {
                cboHorario.setSelectedIndex(i);
                return;
            }

            if (t.getNombreTurno().equalsIgnoreCase(valor)) {
                cboHorario.setSelectedIndex(i);
                return;
            }
        }
    }
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        int id = 0;
        if (modoEdicion) {
            id = Integer.parseInt(txtCodigo.getText());
        }
        // Relacionar mis variables   
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String especialidad = txtEspecialidad.getText().trim();

        // 2️⃣ Obtener objetos seleccionados del combo
        Area areaSeleccionada = (Area) cboArea.getSelectedItem();
        Turno turnoSeleccionado = (Turno) cboHorario.getSelectedItem();

        int idArea = areaSeleccionada != null ? areaSeleccionada.getIdArea() : 0;
        int idTurno = turnoSeleccionado != null ? turnoSeleccionado.getIdTurno() : 0;

        // 3️⃣ Validar
        if (nombre.isEmpty() || apellido.isEmpty() || especialidad.isEmpty()
                || areaSeleccionada == null || turnoSeleccionado == null
                || turnoSeleccionado.getIdTurno() == 0 || areaSeleccionada.getIdArea() == 0) {
            JOptionPane.showMessageDialog(this, "⚠️ Todos los campos son obligatorios y válidos.");
            return;
        }

        // Crear objeto Usuario
        Trabajador t = new Trabajador(0, "----Seleccione Trabajador----");
        t.setNombres(nombre);
        t.setApellidos(apellido);
        t.setEspecialidad(especialidad);
        t.setHorario(String.valueOf(idTurno)); // o también puedes usar int directamente
        t.setCodArea(String.valueOf(idArea)); // si usas String internamente

        // 🔹 Determinar el estado según el rol
        if (usuarioActual instanceof Administrador) {
            Administrador admin = (Administrador) usuarioActual;

            if (admin.getTipo() == Administrador.Tipo.Completo) {
                t.setEstado(chkEstado.isSelected()); // Completo puede elegir
            } else {
                t.setEstado(true); // Limitado siempre activo
                chkEstado.setSelected(true);         // Mostrar activo
            }
        } else {
            // Otros usuarios siempre activo
            t.setEstado(true);
            chkEstado.setSelected(true);
        }

        // ⃣ Instanciar controlador
        trabajadorController controlador = new trabajadorController();

        if (modoEdicion) {
            // 🔹 Actualizar
            t.setId(idTrabajadorEditar); // Asignar ID para editar
            boolean actualizado = controlador.actualizarTrabajador(t);

            if (actualizado) {
                JOptionPane.showMessageDialog(this, "✅ Trabajador actualizado correctamente.");
                Limpiar(); // limpiar campos
                dispose(); // cerrar formulario
            } else {
                JOptionPane.showMessageDialog(this, "❌ Error al actualizar trabajador.");
                System.out.println("Turno ID: " + turnoSeleccionado.getIdTurno());
                System.out.println("Área ID: " + areaSeleccionada.getIdArea());

            }

        } else {
            // 🔹 Registrar nuevo
            boolean registrado = controlador.registrarTrabajador(t);
            if (registrado) {
                JOptionPane.showMessageDialog(this, "✅ Trabajador registrado correctamente.");
                Limpiar(); // limpiar campos
            } else {
                JOptionPane.showMessageDialog(this, "❌ Error al registrar trabajador.");
                System.out.println("Turno ID: " + turnoSeleccionado.getIdTurno());
                System.out.println("Área ID: " + areaSeleccionada.getIdArea());
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    // 🔹 Carga los datos del trabajador en los campos del formulario
    public void cargarDatosParaEditar(Trabajador t) {
        if (t == null) {
            JOptionPane.showMessageDialog(this, "⚠️ No se han recibido datos para editar.");
            return;
        }
        // Cambia el modo a edición
        this.modoEdicion = true;
        // Guarda el ID del trabajador en una variable global
        this.idTrabajadorEditar = t.getId();
        // Cambia el título del formulario 
        this.setTitle("Editar Trabajador");

        // Rellena los campos con los datos actuales
        txtCodigo.setText(String.valueOf(t.getId()));
        txtNombre.setText(t.getNombres());
        txtApellido.setText(t.getApellidos());
        txtEspecialidad.setText(t.getEspecialidad());
        // 🔹 Aquí puede venir el ID o el nombre dependiendo de tu procedimiento almacenado
        txtHorario.setText(t.getHorario());
        txtArea.setText(t.getCodArea());

        // 🔹 Reflejar el estado booleano en el JCheckBox
        chkEstado.setSelected(t.isEstado());

        // 🔹 Aplicar permisos según rol
        aplicarPermisosTrabajador();

        // Esperar a que los combos terminen de cargar
        SwingUtilities.invokeLater(() -> {
            seleccionarArea(txtArea.getText().trim());
            seleccionarTurno(txtHorario.getText().trim());
        });
        // Cambiar el texto del botón principal
        btnRegistrar.setText("ACTUALIZAR");
    }
    private void btnVolverDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverDashboardActionPerformed
        // Obtener el desktopPane del formulario padre
        JDesktopPane desktopPane = this.getDesktopPane();
        if (desktopPane == null) {
            System.err.println("⚠️ No se pudo acceder al desktopPane del padre.");
            return;
        }

        frmDashboard dasbboardForm = null;

        // Recorremos los frames existentes
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            if (frame instanceof frmNuevoUsuario) { // verificar la clase correcta
                dasbboardForm = (frmDashboard) frame;
                break;
            }
        }

        // Si ya existe, traerlo al frente
        if (dasbboardForm != null) {
            try {
                dasbboardForm.setIcon(false); // si estaba minimizado
                dasbboardForm.setSelected(true);
                dasbboardForm.toFront();
            } catch (PropertyVetoException e) {
                e.printStackTrace();
            }
        } else {
            // Si no existe, crear nueva instancia y agregar al desktopPane
            dasbboardForm = new frmDashboard();
            desktopPane.add(dasbboardForm);
            dasbboardForm.setVisible(true);
        }
    }//GEN-LAST:event_btnVolverDashboardActionPerformed

    private void cboHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHorarioActionPerformed
        // TODO add your handling code here:
        Turno turno = (Turno) cboHorario.getSelectedItem();
        if (turno != null) {
            txtHorario.setText(String.valueOf(turno.getIdTurno()));
        }
    }//GEN-LAST:event_cboHorarioActionPerformed

    private void cboAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAreaActionPerformed
        // TODO add your handling code here:
        Area area = (Area) cboArea.getSelectedItem();
        if (area != null) {
            txtArea.setText(String.valueOf(area.getIdArea()));
        }
    }//GEN-LAST:event_cboAreaActionPerformed


    private void txtHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorarioActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_txtHorarioActionPerformed

    private void txtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_txtAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNuevoTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNuevoTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNuevoTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNuevoTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNuevoTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolverDashboard;
    private javax.swing.JComboBox<Area> cboArea;
    private javax.swing.JComboBox<Turno> cboHorario;
    private javax.swing.JCheckBox chkEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
