package vistas;

import clases.Administrador;
import clases.Area;
import clases.Cita;
import clases.Cliente;
import clases.Servicio;
import clases.SesionUsuario;
import clases.Trabajador;
import clases.Usuario;
import clasesDAO.citaDAO;
import controlador.areaController;
import controlador.citaController;
import controlador.clienteController;
import controlador.servicioController;
import controlador.trabajadorController;
import java.text.ParseException;
import java.util.List;
import javax.swing.*;
import javax.swing.JInternalFrame;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DateFormatter;
import javax.swing.text.DocumentFilter;
import util.Iconos;

/**
 *
 * @author v1ct0
 */
public class frmNuevaCita extends JInternalFrame {

    private javax.swing.JPanel overlayPanel;

    /**
     * Creates new form CrearCitaForm
     */
    private Timer timerVencimiento;
    private Usuario usuarioActual;

    public frmNuevaCita() {
        initComponents();
        Iconos();
        this.usuarioActual = SesionUsuario.getUsuarioActual(); // 🔹 recupera usuario en sesión

        iniciarTemporizadorVencimiento();
        // ⚙ Inicialización general        
        habilitarCampos();
        BloquearFechaAnterior();
        configurarSpinnerHora();
        cargarCombos();

        aplicarSegunPermisos();
        Ocultar();
        configurarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnVolverDashboard = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        dtFecha = new com.toedter.calendar.JDateChooser();
        cboCliente = new javax.swing.JComboBox<>();
        cboServicio = new javax.swing.JComboBox<>();
        cboTrabajador = new javax.swing.JComboBox<>();
        cboArea = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        txtServicio = new javax.swing.JTextField();
        txtTrabajador = new javax.swing.JTextField();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.MINUTE);
        jsHora = new javax.swing.JSpinner(sm);
        lblHoraFin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("REGISTRO DE CITA");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setText("Cliente:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setText("Fecha:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("Hora:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setText("Area:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setText("Trabajador:");

        btnRegistrar.setBackground(new java.awt.Color(76, 175, 80));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar-datos.png"))); // NOI18N
        btnRegistrar.setText("GUARDAR");
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(244, 67, 54));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnVolverDashboard.setBackground(new java.awt.Color(240, 240, 240));
        btnVolverDashboard.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVolverDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datos.png"))); // NOI18N
        btnVolverDashboard.setText("Dashboard");
        btnVolverDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverDashboardActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel8.setText("Estado:");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el Estado:", "Pendiente", "Atendida", " " }));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel9.setText("Observaciones:");

        txtObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacionesActionPerformed(evt);
            }
        });

        dtFecha.setDateFormatString("yyyy/MM/dd");
        dtFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtFechaPropertyChange(evt);
            }
        });

        cboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClienteActionPerformed(evt);
            }
        });

        cboServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboServicioActionPerformed(evt);
            }
        });

        cboTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTrabajadorActionPerformed(evt);
            }
        });

        cboArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAreaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel10.setText("Servicio:");

        JSpinner.DateEditor de = new JSpinner.DateEditor(jsHora, "HH:mm");
        jsHora.setEditor(de);

        lblHoraFin.setText("--:--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnVolverDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(552, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboTrabajador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboEstado, 0, 175, Short.MAX_VALUE)
                                    .addComponent(cboArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtObservaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jsHora, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jLabel7)
                                .addContainerGap(132, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(188, 188, 188))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolverDashboard)))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jsHora)
                            .addComponent(lblHoraFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean modoEdicion = false;
    private int idCitaEditar = -1;

    private void Iconos(){
        // Asignar iconos
        btnRegistrar.setIcon(Iconos.get("guardar-datos.png"));
        btnCancelar.setIcon(Iconos.get("cancelar.png"));
        btnVolverDashboard.setIcon(Iconos.get("datos.png"));
    }
    private void configurarVentana() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setClosable(true);
        setIconifiable(false);
        setMaximizable(false);
        setResizable(false);
        this.setTitle("Registro Cita");
    }

    // 🔓 Habilitar todos los campos (modo nueva cita)
    public void habilitarCampos() {
        cboCliente.setEnabled(true);
        cboTrabajador.setEnabled(true);
        cboArea.setEnabled(true);
        cboServicio.setEnabled(true);
        dtFecha.setEnabled(true);
        jsHora.setEnabled(true);
        cboEstado.setEnabled(true);
        txtObservaciones.setEnabled(true);

        btnRegistrar.setText("REGISTRAR");
        this.modoEdicion = false;
        this.idCitaEditar = 0;
    }

    public void BloquearFechaAnterior() {
        // 🔹 Configuración del JDateChooser
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);

        // Establecer la fecha mínima como hoy
        dtFecha.setMinSelectableDate(cal.getTime());

        // Hacer que el campo del JDateChooser no se pueda escribir manualmente
        ((JTextField) dtFecha.getDateEditor().getUiComponent()).setEditable(false);
    }

    public void configurarEstadoPendiente() {
        cboEstado.setSelectedItem("Pendiente");
        cboEstado.setEnabled(false); // deshabilitado
    }

    private void Ocultar() {
        // 🔹 Ocultar label y campo de código
        txtTrabajador.setVisible(false);
        txtArea.setVisible(false);
        txtServicio.setVisible(false);

        // 🔹 Bloquear (por si lo muestras luego)
        txtArea.setEditable(false);
        configurarEstadoPendiente();
    }

    private void aplicarSegunPermisos() {
        Usuario u = SesionUsuario.getUsuarioActual();

        if (u == null) {
            return;
        }

        List<String> permisos = u.getPermisos();

        // 🔐 Registrar nueva cita
        if (!permisos.contains("Registrar_Cita") && !modoEdicion) {
            btnRegistrar.setEnabled(false);
        }

        // 🔐 Actualizar cita (solo modo edición)
        if (!permisos.contains("Actualizar_Cita") && modoEdicion) {
            btnRegistrar.setEnabled(false);
        }

    }

    // 🗓️ Cargar combos al iniciar el formulario
    private void cargarCombos() {
        clienteController clienteCtrl = new clienteController();
        trabajadorController trabajadorCtrl = new trabajadorController();
        areaController areaCtrl = new areaController();

        // --- CLIENTE ---
        cboCliente.removeAllItems();
        cboCliente.addItem(new Cliente(0, "----Seleccione Cliente----"));
        for (Cliente c : clienteCtrl.listarClientes()) {
            cboCliente.addItem(c);
        }
        // --- TRABAJADOR ---
        cboTrabajador.removeAllItems();
        cboTrabajador.addItem(new Trabajador(0, "----Seleccione Trabajador----"));
        for (Trabajador t : trabajadorCtrl.listarTrabajadores()) {
            cboTrabajador.addItem(t);
        }

        // --- ÁREA ---
        cboArea.removeAllItems();
        cboArea.addItem(new Area(0, "----Seleccione un área----"));
        for (Area a : areaCtrl.obtenerAreas()) {
            cboArea.addItem(a);
        }

        // --- SERVICIO ---
        cboServicio.removeAllItems();
        cboServicio.addItem(new Servicio(0, "----Seleccione un servicio----"));

    }

    private void cargarAreas() {
        areaController controller = new areaController();
        List<Area> lista = controller.obtenerAreas();

        cboArea.removeAllItems();
        cboArea.addItem(new Area(0, "----Seleccione un área----"));
        for (Area a : lista) {
            cboArea.addItem(a);
        }

        // Al iniciar, también mostrar solo el texto por defecto en servicios
        cboServicio.removeAllItems();
        cboServicio.addItem(new Servicio(0, "----Seleccione un servicio----"));
    }

    private void cargarServiciosPorArea(int idArea) {
        servicioController controller = new servicioController();
        List<Servicio> lista = controller.listarPorArea(idArea);

        cboServicio.removeAllItems();
        cboServicio.addItem(new Servicio(0, "----Seleccione un servicio----"));
        for (Servicio s : lista) {
            cboServicio.addItem(s);
        }
    }

    private void seleccionarItem(JComboBox combo, int id) {
        for (int i = 0; i < combo.getItemCount(); i++) {
            Object obj = combo.getItemAt(i);
            if (obj instanceof Cliente && ((Cliente) obj).getId() == id) {
                combo.setSelectedIndex(i);
                break;
            } else if (obj instanceof Trabajador && ((Trabajador) obj).getId() == id) {
                combo.setSelectedIndex(i);
                break;
            } else if (obj instanceof Servicio && ((Servicio) obj).getIdServicio() == id) {
                combo.setSelectedIndex(i);
                break;
            } else if (obj instanceof Area && ((Area) obj).getIdArea() == id) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        new frmDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVolverDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverDashboardActionPerformed
        // TODO add your handling code here:
        new frmDashboard().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVolverDashboardActionPerformed

    private void txtObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacionesActionPerformed

    private void calcularHoraFin() {
        try {
            Servicio servicio = (Servicio) cboServicio.getSelectedItem();
            if (servicio == null || servicio.getIdServicio() == 0) {
                lblHoraFin.setText("--:--");
                return;
            }

            int duracion = servicio.getDuracion(); // minutos del servicio

            // Obtener hora inicio desde el JSpinner
            java.util.Date horaIni = (java.util.Date) jsHora.getValue();
            LocalTime horaInicio = horaIni.toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalTime();

            // Calcular hora fin
            LocalTime horaFin = horaInicio.plusMinutes(duracion);

            // Mostrar en Label
            lblHoraFin.setText(horaFin.toString()); // formato HH:mm

        } catch (Exception e) {
            lblHoraFin.setText("--:--");
        }
    }

    private void verificarVencimientoServicio() {
        try {
            if (!this.isVisible()) {
                return;   // si el formulario no está visible, NO NOTIFICAR
            }

            String horaFinTexto = lblHoraFin.getText();

            if (horaFinTexto.equals("--:--")) {
                return;
            }

            LocalTime horaFin = LocalTime.parse(horaFinTexto);
            LocalTime horaActual = LocalTime.now();

            if (!horaActual.isBefore(horaFin)) {
                JOptionPane.showMessageDialog(
                        this,
                        "⚠ El tiempo asignado para este servicio ya venció.\n"
                        + "Hora fin: " + horaFin + "\n"
                        + "Hora actual: " + horaActual + "\n\n"
                        + "Por favor actualice el estado a 'Atendido'.",
                        "Servicio vencido",
                        JOptionPane.WARNING_MESSAGE
                );
            }
        } catch (Exception e) {
            // No hacer nada
        }
    }

    private void iniciarTemporizadorVencimiento() {
        Timer timer = new Timer(60000, e -> verificarVencimientoServicio()); // cada 1 minuto
        timer.start();

    }

    @Override
    public void dispose() {
        if (timerVencimiento != null) {
            timerVencimiento.stop();
        }
        super.dispose();
    }

    public void configurarSpinnerHora() {

        // 🔹 Modelo de hora
        SpinnerDateModel model = new SpinnerDateModel();
        jsHora.setModel(model);

        // 🔹 Formato HH:mm
        SimpleDateFormat format = new SimpleDateFormat("HH:mm");
        JSpinner.DateEditor editor = new JSpinner.DateEditor(jsHora, "HH:mm");
        jsHora.setEditor(editor);

        // 🔹 Configurar edición manual con validación
        JFormattedTextField tf = ((JSpinner.DefaultEditor) jsHora.getEditor()).getTextField();
        DateFormatter dateFormatter = (DateFormatter) tf.getFormatter();
        dateFormatter.setAllowsInvalid(false); // ❌ No permite caracteres inválidos
        dateFormatter.setOverwriteMode(true);   // 🔹 Sobrescribe en vez de insertar
        dateFormatter.setFormat(format);

        // 🔹 Validación por cada tecla (evita escribir >23h o >59m)
        ((AbstractDocument) tf.getDocument()).setDocumentFilter(new DocumentFilter() {

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                    throws BadLocationException {
                validar(fb, offset, length, text, attrs);
            }

            @Override
            public void insertString(FilterBypass fb, int offset, String text, AttributeSet attrs)
                    throws BadLocationException {
                validar(fb, offset, 0, text, attrs);
            }

            private void validar(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                    throws BadLocationException {

                String actual = fb.getDocument().getText(0, fb.getDocument().getLength());
                StringBuilder nuevo = new StringBuilder(actual);
                nuevo.replace(offset, offset + length, text);

                // No permitir más de 5 caracteres (HH:mm)
                if (nuevo.length() > 5) {
                    return;
                }

                // Solo números excepto en la posición 2 que es ":"
                for (int i = 0; i < nuevo.length(); i++) {
                    char c = nuevo.charAt(i);

                    if (i == 2) {
                        if (c != ':') {
                            return; // posición del ":"
                        }
                    } else {
                        if (!Character.isDigit(c)) {
                            return; // solo dígitos
                        }
                    }
                }

                // Validar HH
                if (nuevo.length() >= 2) {
                    int h = Integer.parseInt(nuevo.substring(0, 2));
                    if (h > 23) {
                        return;
                    }
                }

                // Validar mm
                if (nuevo.length() == 5) {
                    int m = Integer.parseInt(nuevo.substring(3, 5));
                    if (m > 59) {
                        return;
                    }
                }

                // Aplicar si todo es válido
                super.replace(fb, offset, length, text, attrs);
            }
        });

        // 🔹 Validar al perder foco
        tf.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                try {
                    tf.commitEdit(); // Aplica el valor escrito
                    Date d = (Date) jsHora.getValue();
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(d);

                    int h = cal.get(Calendar.HOUR_OF_DAY);
                    int m = cal.get(Calendar.MINUTE);

                    // Validar límites finales
                    if (h > 23) {
                        h = 23;
                    }
                    if (m > 59) {
                        m = 59;
                    }

                    cal.set(Calendar.HOUR_OF_DAY, h);
                    cal.set(Calendar.MINUTE, m);
                    jsHora.setValue(cal.getTime());

                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Formato inválido, use HH:mm");
                    jsHora.setValue(new Date()); // Reset a hora actual
                }
            }
        });
    }

    private boolean validarSolapamientoPrevio() {
        try {
            java.sql.Date fechaSQL = new java.sql.Date(dtFecha.getDate().getTime());
            java.sql.Time horaSQL = new java.sql.Time(((Date) jsHora.getValue()).getTime());
            int idTrabajador = ((Trabajador) cboTrabajador.getSelectedItem()).getId();
            int idServicio = ((Servicio) cboServicio.getSelectedItem()).getIdServicio();

            // Llamar método DAO temporal que VERIFIQUE y no registre
            citaDAO dao = new citaDAO();
            int resultado = dao.validarSolapamiento(fechaSQL, horaSQL, idTrabajador, idServicio);

            return (resultado == -6); // hay choque
        } catch (Exception e) {
            return false;
        }
    }


    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // 🚫 VALIDAR PERMISO PARA REGISTRAR CITA
        Usuario u = SesionUsuario.getUsuarioActual();
        if (u == null || !u.getPermisos().contains("Registrar_Cita")) {
            JOptionPane.showMessageDialog(
                    this,
                    "🚫 No tienes permiso para registrar citas.",
                    "Acceso denegado",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            // ✅ Fecha
            java.util.Date fechaSeleccionada = dtFecha.getDate();
            if (fechaSeleccionada == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "⚠️ Seleccione una fecha.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }
            java.sql.Date fechaSQL = new java.sql.Date(fechaSeleccionada.getTime());

            // ✅ Hora desde JSpinner (formato HH:mm)
            java.util.Date horaSeleccionada = (java.util.Date) jsHora.getValue();
            java.sql.Time horaSQL = new java.sql.Time(horaSeleccionada.getTime());

            // ✅ Obtener elementos seleccionados de los combos
            Cliente cliente = (Cliente) cboCliente.getSelectedItem();
            Trabajador trabajador = (Trabajador) cboTrabajador.getSelectedItem();
            Servicio servicio = (Servicio) cboServicio.getSelectedItem();
            //Area area = (Area) cboArea.getSelectedItem();

            if (cliente == null || cliente.getId() == 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "⚠️ Seleccione un cliente.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }
            // ✅ Obtener el usuario logueado desde SesionUsuario
            Usuario usuarioActual = SesionUsuario.getUsuarioActual();
            if (usuarioActual == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "⚠️ No hay usuario logueado.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }
            citaController controller = new citaController();

            // 🔍 VALIDACIÓN DE SOLAPAMIENTO SOLO SI ES NECESARIO
            boolean validarSolapamiento = true;

            if (modoEdicion) {
                // Obtener la cita original
                Cita citaOriginal = controller.obtenerCitaPorId(idCitaEditar);

                // Si el estado original YA ES atendida/cancelada
                String rol = SesionUsuario.getUsuarioActual().getRol(); // o como obtienes el rol

                // ▪ Validar si el usuario puede editar según su rol y estado de la cita
                if (!controller.puedeEditarCita(citaOriginal, rol)) {
                    JOptionPane.showMessageDialog(
                            this,
                            "🚫 No tienes permiso para editar esta cita.\n"
                            + "Estado actual: " + citaOriginal.getEstadoCita(),
                            "Acceso denegado",
                            JOptionPane.WARNING_MESSAGE
                    );
                    return; // 🔥 Bloquea la edición
                }

                // Comparar cambios
                boolean cambioFecha = !fechaSQL.equals(citaOriginal.getFechaCita());
                boolean cambioHora = !horaSQL.equals(citaOriginal.getHoraCita());
                boolean cambioTrabajador = trabajador.getId() != citaOriginal.getIdTrabajador();
                boolean cambioServicio = servicio.getIdServicio() != citaOriginal.getIdServicio();

                // ⭐ Si SOLO cambia estado u observación → NO validar solapamiento
                if (!cambioFecha && !cambioHora && !cambioTrabajador && !cambioServicio) {
                    validarSolapamiento = false;
                }
            }

            if (validarSolapamiento) {
                int resSolap = controller.validarSolapamiento(
                        fechaSQL,
                        horaSQL,
                        trabajador.getId(),
                        servicio.getIdServicio()
                );

                if (resSolap == -6) {
                    JOptionPane.showMessageDialog(
                            this,
                            "⚠️ El trabajador tiene una cita que se solapa con este horario.",
                            "Advertencia",
                            JOptionPane.WARNING_MESSAGE
                    );
                    return;
                }
            }

            // Crear objeto cita
            Cita cita = new Cita();
            cita.setFechaCita(fechaSQL);
            cita.setHoraCita(horaSQL);
            cita.setEstadoCita(cboEstado.getSelectedItem().toString());
            cita.setObservacionCita(txtObservaciones.getText());
            cita.setIdCliente(cliente.getId());
            cita.setIdTrabajador(trabajador.getId());
            cita.setIdUsuario(usuarioActual.getId()); // ✅ Guarda el ID del usuario 
            cita.setIdServicio(servicio.getIdServicio());

            // -------------------------
            // 5️⃣ REGISTRAR O ACTUALIZAR
            // -------------------------
            boolean resultado;
            String rolUsuario = usuarioActual.getRol();
            if (modoEdicion) {
                cita.setIdCita(idCitaEditar);
                // 🔍 Obtener la cita original para verificar permisos
                Cita citaOriginal = controller.obtenerCitaPorId(idCitaEditar);
                // 🔒 Bloquear edición según estado y rol
                if (!controller.puedeEditarCita(citaOriginal, rolUsuario)) {
                    JOptionPane.showMessageDialog(
                            this,
                            "🚫 No puedes modificar esta cita porque está: "
                            + citaOriginal.getEstadoCita(),
                            "Acceso denegado",
                            JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }

                // ✔ Si tiene permiso → actualizar
                resultado = controller.actualizarCita(cita, rolUsuario);

            } else {
                // ✔ Registrar cita
                resultado = controller.registrarCita(cita);
            }
            // ⭐ Mostrar tipo según el SP
            int tipo = controller.getTipoMensaje();
            String msj = controller.getMensaje();

            switch (tipo) {
                case 0:
                    JOptionPane.showMessageDialog(
                            this, msj, "Error", JOptionPane.ERROR_MESSAGE);
                    break;

                case 1: // ⚠️ Advertencias (-2, -3, -4, -5, -6, -7,-8)
                    JOptionPane.showMessageDialog(
                            this, msj, "Advertencia", JOptionPane.WARNING_MESSAGE);
                    break;

                case 2:
                    JOptionPane.showMessageDialog(
                            this, msj, "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    if (resultado) {
                        dispose();
                    }
                    break;

                default:
                    JOptionPane.showMessageDialog(
                            this, "⚠️ Resultado desconocido.", "Aviso", JOptionPane.WARNING_MESSAGE
                    );
                    break;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "❌ Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void seleccionarAreaPorId(int idArea) {
        for (int i = 0; i < cboArea.getItemCount(); i++) {
            Area a = cboArea.getItemAt(i);
            if (a.getIdArea() == idArea) {
                cboArea.setSelectedIndex(i);
                break;
            }
        }
    }

    private void seleccionarServicioPorId(int idServicio) {
        for (int i = 0; i < cboServicio.getItemCount(); i++) {
            Servicio s = cboServicio.getItemAt(i);
            if (s.getIdServicio() == idServicio) {
                cboServicio.setSelectedIndex(i);
                break;
            }
        }
    }
    private void cboAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAreaActionPerformed
        // Cuando el usuario selecciona un área
        Area areaSeleccionada = (Area) cboArea.getSelectedItem();

        if (areaSeleccionada != null && areaSeleccionada.getIdArea() > 0) {
            // Guarda el ID del área en un textfield oculto (si lo usas)
            txtArea.setText(String.valueOf(areaSeleccionada.getIdArea()));

            // Carga los servicios según el área
            cargarServiciosPorArea(areaSeleccionada.getIdArea());
        } else {
            // Limpia el combo de servicios si no hay área válida
            cboServicio.removeAllItems();
            cboServicio.addItem(new Servicio(0, "----Seleccione un servicio----"));
        }
    }//GEN-LAST:event_cboAreaActionPerformed

    private void cboServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboServicioActionPerformed
        Servicio servicio = (Servicio) cboServicio.getSelectedItem();

        if (servicio != null && servicio.getIdServicio() > 0) {
            txtServicio.setText(String.valueOf(servicio.getIdServicio()));
        } else {
            txtServicio.setText("");
        }
        // 1. Calcular la hora fin con base en la duración del servicio
        calcularHoraFin();

        // 2. Verificar si ya venció el tiempo del servicio
        verificarVencimientoServicio();
    }//GEN-LAST:event_cboServicioActionPerformed

    private void dtFechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtFechaPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            // Se seleccionó una fecha
            java.util.Date fechaSeleccionada = dtFecha.getDate();
            if (fechaSeleccionada != null) {
                // Obtener la hora actual
                java.util.Date ahora = new java.util.Date();
                SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
            }
        }
    }//GEN-LAST:event_dtFechaPropertyChange

    private void cboTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTrabajadorActionPerformed
        Trabajador trabajador = (Trabajador) cboTrabajador.getSelectedItem();
        if (trabajador != null) {
            txtTrabajador.setText(String.valueOf(trabajador.getId()));
        }
    }//GEN-LAST:event_cboTrabajadorActionPerformed

    private void cboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboClienteActionPerformed

    // 🧩 Cargar datos en modo edición
    public void cargarDatosParaEditar(Cita cita) {
        if (cita == null) {
            JOptionPane.showMessageDialog(this, "⚠️ No se recibieron datos de cita para editar.");
            return;
        }
        try {
            // Cambia el modo a edición
            this.modoEdicion = true;
            this.idCitaEditar = cita.getIdCita(); // variable global para saber qué cita se edita
            this.setTitle("Editar Cita");

            // Rol del usuario
            String rolUsuario = usuarioActual.getRol();
            citaController controller = new citaController();
            boolean puedeEditar = controller.puedeEditarCita(cita, rolUsuario);

            // 📅 Fecha de cita
            try {
                if (cita.getFechaCita() != null) {
                    dtFecha.setDate(cita.getFechaCita()); // JDateChooser acepta java.util.Date
                }
            } catch (Exception e) {
                System.err.println("Error cargando fecha: " + e.getMessage());
            }

            // ⏰ Hora
            try {
                if (cita.getHoraCita() != null) {
                    jsHora.setValue(cita.getHoraCita()); // o el componente que uses (ej. JSpinner)
                }
            } catch (Exception e) {
                System.err.println("Error cargando hora: " + e.getMessage());
            }

            // 🔹 Estado
            if (cita.getEstadoCita() != null) {
                cboEstado.setSelectedItem(cita.getEstadoCita());
            }

            // 🔹 Observación (si existe)
            txtObservaciones.setText(cita.getObservacionCita() != null ? cita.getObservacionCita() : "");

            // 🔹 CLIENTE
            if (cboCliente.getItemCount() > 0) {
                for (int i = 0; i < cboCliente.getItemCount(); i++) {
                    Cliente c = (Cliente) cboCliente.getItemAt(i);
                    String nombreCompletoCliente = c.getNombre() + " " + c.getApellido();
                    if (nombreCompletoCliente.equalsIgnoreCase(cita.getNombreCliente())) {
                        cboCliente.setSelectedIndex(i);
                        break;
                    }
                }
            }

            // 🔹 TRABAJADOR
            if (cboTrabajador.getItemCount() > 0) {
                for (int i = 0; i < cboTrabajador.getItemCount(); i++) {
                    Trabajador t = (Trabajador) cboTrabajador.getItemAt(i);
                    String nombreCompletoTrabajador = t.getNombres() + " " + t.getApellidos();
                    if (nombreCompletoTrabajador.equalsIgnoreCase(cita.getNombreTrabajador())) {
                        cboTrabajador.setSelectedIndex(i);
                        break;
                    }
                }
            }

            // 🏠 ÁREA
            if (cita.getIdArea() > 0) {
                // 🔹 Selecciona el área correspondiente
                seleccionarAreaPorId(cita.getIdArea());
                // 🔹 Carga los servicios de esa área
                cargarServiciosPorArea(cita.getIdArea());
            }

            // 💇‍♀️ SERVICIO
            if (cita.getIdServicio() > 0 && cboServicio.getItemCount() > 0) {
                for (int i = 0; i < cboServicio.getItemCount(); i++) {
                    Servicio s = (Servicio) cboServicio.getItemAt(i);
                    if (s.getIdServicio() == cita.getIdServicio()) {
                        cboServicio.setSelectedIndex(i);
                        break;
                    }
                }
            }

            // ---------- Bloqueo según permisos ----------
            boolean esAdminCompleto = usuarioActual instanceof Administrador
                    && ((Administrador) usuarioActual).getTipo() == Administrador.Tipo.Completo;

            if (!puedeEditar && !esAdminCompleto) {
                // Cita cerrada o anulada → bloquear combobox, fecha y hora
                bloquearCombos(true);
                jsHora.setEnabled(false);
                dtFecha.setEnabled(false);
            } else {
                // Usuario con permisos → habilitar según rol
                if (usuarioActual instanceof Administrador) {
                    cboCliente.setEnabled(true);
                    cboTrabajador.setEnabled(true);
                    cboArea.setEnabled(true);
                    cboServicio.setEnabled(true);
                    txtObservaciones.setEditable(true);
                    cboEstado.setEnabled(esAdminCompleto);
                } else if ("Recepcionista".equalsIgnoreCase(rolUsuario)) {
                    cboCliente.setEnabled(true);
                    cboTrabajador.setEnabled(true);
                    cboArea.setEnabled(true);
                    cboServicio.setEnabled(true);
                    cboEstado.setEnabled(true);
                    txtObservaciones.setEditable(true);
                } else {
                    // Otros usuarios no pueden editar nada
                    bloquearCombos(true);
                    cboEstado.setEnabled(false);
                    txtObservaciones.setEditable(false);
                }
            }

            // Cambiar texto del botón
            btnRegistrar.setText("ACTUALIZAR");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "❌ Error al cargar los datos de la cita: " + e.getMessage());
        }
    }

    private void bloquearCombos(boolean bloquear) {
        cboCliente.setEnabled(!bloquear);
        cboTrabajador.setEnabled(!bloquear);
        cboArea.setEnabled(!bloquear);
        cboServicio.setEnabled(!bloquear);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNuevaCita.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNuevaCita.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNuevaCita.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNuevaCita.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmNuevaCita frame = new frmNuevaCita();
                frame.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolverDashboard;
    private javax.swing.JComboBox<Area> cboArea;
    private javax.swing.JComboBox<Cliente> cboCliente;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<Servicio> cboServicio;
    private javax.swing.JComboBox<Trabajador> cboTrabajador;
    private com.toedter.calendar.JDateChooser dtFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jsHora;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtTrabajador;
    // End of variables declaration//GEN-END:variables
}
