package vistas;

import clases.Area;
import clases.Servicio;
import clases.SesionUsuario;
import clases.Usuario;
import clasesDAO.areaDAO;
import clasesDAO.servicioDAO;
import controlador.servicioController;
import controlador.areaController;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import util.Iconos;

/**
 *
 * @author Administrador
 */
public class frmNuevoServicio extends JInternalFrame {

    /**
     * Creates new form frmNuevoServicio
     */
    private Usuario usuarioActual;

    public frmNuevoServicio() {
        initComponents();
        Iconos();
        actualizarComboAreas();

        // Configuración correcta para JInternalFrame
        this.setClosable(true);
        this.setIconifiable(false);
        this.setMaximizable(false);
        this.setResizable(false);
        this.setTitle("Registrar Servicio");
        this.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNuevaArea = new javax.swing.JTextField();
        txtServicio = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnVolverDashboard = new javax.swing.JButton();
        cboAreas = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Registro de Servicio");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setText("Listado:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel3.setText("Servicio:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel4.setText("Precio:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel5.setText("Duracion:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel6.setText("Observacion:");

        txtNuevaArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNuevaAreaKeyTyped(evt);
            }
        });

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        txtDuracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDuracionKeyTyped(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(244, 67, 54));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(76, 175, 80));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar-datos.png"))); // NOI18N
        btnRegistrar.setText("GUARDAR");
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnVolverDashboard.setBackground(new java.awt.Color(240, 240, 240));
        btnVolverDashboard.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVolverDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datos.png"))); // NOI18N
        btnVolverDashboard.setText("Dashboard");
        btnVolverDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverDashboardActionPerformed(evt);
            }
        });

        cboAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAreasActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel7.setText("Area:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(50, 50, 50)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cboAreas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDuracion)
                                        .addComponent(txtServicio)
                                        .addComponent(txtPrecio)
                                        .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtNuevaArea, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnVolverDashboard)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolverDashboard)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtNuevaArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Modo edición
    private boolean modoEdicion = false;
    private int idServicioEditar = -1;
    private int idAreaEditar = 0;            // ID del área que se está editando

    private void Iconos() {
        // Asignar iconos
        btnRegistrar.setIcon(Iconos.get("guardar-datos.png"));
        btnCancelar.setIcon(Iconos.get("cancelar.png"));
        btnVolverDashboard.setIcon(Iconos.get("datos.png"));
    }

    private void Limpiar() {
        txtNuevaArea.setText("");
        txtServicio.setText("");
        txtPrecio.setText("");
        txtDuracion.setText("");
        txtObservacion.setText("");
    }

    private void actualizarComboAreas() {
        areaController controller = new areaController();
        List<Area> lista = controller.obtenerAreas();  // ✔ Ahora viene del controller

        cboAreas.removeAllItems();
        cboAreas.addItem(new Area(0, "----Seleccione un área----"));
        for (Area a : lista) {
            cboAreas.addItem(a);
        }
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        new frmDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        // 1️⃣ Capturar datos del formulario
        String nombreServicio = txtServicio.getText().trim();
        String precioStr = txtPrecio.getText().trim();
        String duracionStr = txtDuracion.getText().trim();
        String nombreNuevaArea = txtNuevaArea.getText().trim();

        // Área seleccionada del combo
        Area areaSeleccionada = (Area) cboAreas.getSelectedItem();

        // Validar campos obligatorios
        if (nombreServicio.isEmpty() || precioStr.isEmpty() || duracionStr.isEmpty()
                || (areaSeleccionada == null && nombreNuevaArea.isEmpty())) {
            JOptionPane.showMessageDialog(this, "⚠️ Todos los campos son obligatorios.");
            return;
        }
        double precio;
        int duracion;

        try {
            precio = Double.parseDouble(precioStr);
            duracion = Integer.parseInt(duracionStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "⚠️ Precio o duración no son válidos.");
            return;
        }

        // 2️⃣ Crear objeto Servicio
        Servicio s = new Servicio();
        s.setNombre(nombreServicio);
        s.setPrecio(precio);
        s.setDuracion(duracion);
        s.setArea(areaSeleccionada);  // atributo nuevo en DTO

        // 3️⃣ Llamar al controller
        servicioController sc = new servicioController();
        boolean exito;
        if (modoEdicion) {
            s.setIdServicio(idServicioEditar); // si está editando
            exito = sc.actualizar(s);
        } else {
            exito = sc.registrar(s);
        }

        // 5️⃣ Mostrar mensaje según el DAO
        switch (sc.getTipoMensaje()) {
            case 0:
                JOptionPane.showMessageDialog(this, sc.getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case 1:
                JOptionPane.showMessageDialog(this, sc.getMensaje(), "Advertencia", JOptionPane.WARNING_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(this, sc.getMensaje(), "Éxito", JOptionPane.INFORMATION_MESSAGE);
                Limpiar(); // limpiar campos
                actualizarComboAreas(); // actualizar combo si es nueva área
                break;
            default:
                JOptionPane.showMessageDialog(this, "Resultado desconocido: " + sc.getMensaje());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    // 🔹 Cargar datos del servicio seleccionado
    public void cargarDatosParaEditar(Servicio s) {
        if (s == null) {
            JOptionPane.showMessageDialog(this, "⚠️ No se han recibido datos para editar.");
            return;
        }

        // Cambia el formulario a modo EDICIÓN
        this.modoEdicion = true;
        this.idServicioEditar = s.getIdServicio(); // <-- Guardar ID para actualizar
        this.setTitle("Editar Servicio");

        // Llenar campos
        txtNuevaArea.setText(String.valueOf(s.getArea().getIdArea()));

        // 1️⃣ Actualizar combo de áreas
        actualizarComboAreas(); // Llenamos el combo con todas las áreas

        // 2️⃣ Seleccionar el área del servicio
        for (int i = 0; i < cboAreas.getItemCount(); i++) {
            Area a = (Area) cboAreas.getItemAt(i);
            if (a.getIdArea() == s.getArea().getIdArea()) {
                cboAreas.setSelectedIndex(i);
                break;
            }
        }

        // 1️⃣ Seleccionar área en el combo según el objeto Area del servicio
        cboAreas.setSelectedItem(s.getArea());

        txtServicio.setText(s.getNombre());
        txtDuracion.setText(String.valueOf(s.getDuracion()));
        txtPrecio.setText(String.valueOf(s.getPrecio()));

        // Permisos del usuario (si lo usas)
        //aplicarPermisosServicio();
        // Cambiar texto del botón principal
        btnRegistrar.setText("ACTUALIZAR");
    }

    private void btnVolverDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverDashboardActionPerformed
        // Obtener el desktopPane del formulario padre
        JDesktopPane desktopPane = this.getDesktopPane();
        if (desktopPane == null) {
            System.err.println("⚠️ No se pudo acceder al desktopPane del padre.");
            return;
        }

        frmDashboard dasbboardForm = null;

        // Recorremos los frames existentes
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            if (frame instanceof frmNuevoUsuario) { // verificar la clase correcta
                dasbboardForm = (frmDashboard) frame;
                break;
            }
        }

        // Si ya existe, traerlo al frente
        if (dasbboardForm != null) {
            try {
                dasbboardForm.setIcon(false); // si estaba minimizado
                dasbboardForm.setSelected(true);
                dasbboardForm.toFront();
            } catch (PropertyVetoException e) {
                e.printStackTrace();
            }
        } else {
            // Si no existe, crear nueva instancia y agregar al desktopPane
            dasbboardForm = new frmDashboard();
            desktopPane.add(dasbboardForm);
            dasbboardForm.setVisible(true);
        }
    }//GEN-LAST:event_btnVolverDashboardActionPerformed

    private void cboAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAreasActionPerformed
        Area area = (Area) cboAreas.getSelectedItem();
        if (area != null && area.getIdArea() != 0) {
            // Mostrar el nombre del área en el textbox
            txtNuevaArea.setText(area.getNombreArea());
            // Preparar modo edición
            modoEdicion = true;
            idAreaEditar = area.getIdArea();
            btnAgregar.setText("Editar"); // Cambiar texto del botón

        } else {
            // Item por defecto
            txtNuevaArea.setText("");
            modoEdicion = false;
            idAreaEditar = 0;
            btnAgregar.setText("Agregar");
            //Opcional
            txtObservacion.setText("");
        }
    }//GEN-LAST:event_cboAreasActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombreNuevaArea = txtNuevaArea.getText().trim();
        if (nombreNuevaArea.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del área.");
            return;
        }

        Area a = new Area();
        a.setNombreArea(nombreNuevaArea);

        areaController ac = new areaController();
        boolean exito;
        if (modoEdicion) {
            a.setIdArea(idAreaEditar); // si estás editando
            exito = ac.actualizar(a);
        } else {
            exito = ac.registrar(a);
        }

        switch (ac.getTipoMensaje()) {
            case 0:
                JOptionPane.showMessageDialog(this, ac.getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case 1:
                JOptionPane.showMessageDialog(this, ac.getMensaje(), "Advertencia", JOptionPane.WARNING_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(this, ac.getMensaje(), "Éxito", JOptionPane.INFORMATION_MESSAGE);
                txtNuevaArea.setText("");
                actualizarComboAreas();
                modoEdicion = false;
                idAreaEditar = 0;
                btnAgregar.setText("Agregar");
                break;
            default:
                JOptionPane.showMessageDialog(this, ac.getMensaje(), "Resultado desconocido", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c = evt.getKeyChar();
        String text = txtPrecio.getText();

        // Permitir solo dígitos y un solo punto decimal
        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
            return;
        }

        if (c == '.' && text.contains(".")) {
            // Bloquear si ya hay un punto
            evt.consume();
            return;
        }

        // Limitar la cantidad de caracteres (incluyendo punto)
        if (text.length() >= 6) {
            evt.consume();
        }

    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtDuracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuracionKeyTyped
        char c = evt.getKeyChar();
        // Permitir solo dígitos
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        // Limitar la cantida de dígitos
        if (txtDuracion.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDuracionKeyTyped

    private void txtNuevaAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNuevaAreaKeyTyped
        char c = evt.getKeyChar();
        // Permitir solo letras y espacio
        if (!Character.isLetter(c) && c != ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txtNuevaAreaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNuevoServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolverDashboard;
    private javax.swing.JComboBox<Area> cboAreas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtNuevaArea;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtServicio;
    // End of variables declaration//GEN-END:variables
}
