package vistas;

import clases.Administrador;
import clases.Cliente;
import clases.Distrito;
import clases.SesionUsuario;
import clases.Usuario;
import controlador.clienteController;
import controlador.distritoController;
import java.beans.PropertyVetoException;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import vistas.frmDashboard;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import util.Iconos;

/**
 *
 * @author v1ct0
 */
public class frmNuevoCliente extends JInternalFrame {

    /**
     * Creates new form NuevoClienteForm
     */
    private Usuario usuarioActual;

    public frmNuevoCliente() {
        initComponents();
        Iconos();
        this.usuarioActual = SesionUsuario.getUsuarioActual(); // 🔹 recupera usuario en sesión
        habilitarCampos();
        modoRegistroNuevo();
        cargarDistrito();
        Ocultar();
        Limpiar();
        // Tamaño y centrado
        this.setSize(950, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setClosable(true);      // Mostrar botón de cerrar
        setIconifiable(false);  // Ocultar minimizar
        setMaximizable(false);  // Ocultar maximizar
        setResizable(false);    // Desactivar redimensionar
        this.setTitle("Registro Cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnVolverDashboard = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cboDistrito = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        chkEstado = new javax.swing.JCheckBox();
        txtDistrito = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setText("Nombres:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setText("Email:");

        btnCancelar.setBackground(new java.awt.Color(244, 67, 54));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setText("Teléfono:");

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("REGISTRO DE CLIENTE");

        btnGuardar.setBackground(new java.awt.Color(76, 175, 80));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar-datos.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setFocusPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setText("Apellidos:");

        btnVolverDashboard.setBackground(new java.awt.Color(240, 240, 240));
        btnVolverDashboard.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVolverDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datos.png"))); // NOI18N
        btnVolverDashboard.setText("Dashboard");
        btnVolverDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverDashboardActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Distrito:");

        cboDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDistritoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Estado:");

        lblCodigo.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblCodigo.setText("Codigo:");

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-home-salon-50.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnVolverDashboard)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 434, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(132, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chkEstado)
                                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblCodigo))
                                        .addGap(82, 82, 82)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblImagen))
                    .addComponent(txtDistrito))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnVolverDashboard))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(25, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCodigo)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(chkEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean modoEdicion = false;
    private int idClienteEditar = -1;

    private void Iconos() {
        // Asignar iconos  
        lblImagen.setIcon(Iconos.get("icons8-home-salon-50.png"));
        btnGuardar.setIcon(Iconos.get("guardar-datos.png"));
        btnCancelar.setIcon(Iconos.get("cancelar.png"));
        btnVolverDashboard.setIcon(Iconos.get("datos.png"));
    }

    private void Limpiar() {
        txtNombres.setText("");
        txtApellidos.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
        cboDistrito.setSelectedIndex(0);
        chkEstado.setSelected(true);
    }

    public void habilitarCampos() {
        txtNombres.setEnabled(true);
        txtApellidos.setEnabled(true);
        txtEmail.setEnabled(true);
        txtTelefono.setEnabled(true);
        cboDistrito.setEnabled(true);
        chkEstado.setEnabled(true);

        btnGuardar.setText("REGISTRAR");
        this.modoEdicion = false;
        this.idClienteEditar = 0;
    }

    private void cargarDistrito() {
        distritoController controller = new distritoController();
        List<Distrito> lista = controller.obtenerDistrito();

        cboDistrito.removeAllItems();
        cboDistrito.addItem(new Distrito(0, "----Seleccione un Distrito----"));
        for (Distrito a : lista) {
            cboDistrito.addItem(a);
        }
    }

    private void seleccionarDistrito(String valor) {
        if (valor == null || valor.isEmpty()) {
            return;
        }

        for (int i = 0; i < cboDistrito.getItemCount(); i++) {
            Distrito d = (Distrito) cboDistrito.getItemAt(i);

            // 🔸 Si es numérico, comparar por ID
            if (valor.matches("\\d+") && d.getIdDistrito() == Integer.parseInt(valor)) {
                cboDistrito.setSelectedIndex(i);
                return;
            }

            // 🔸 Si no es numérico, comparar por nombre
            if (d.getNombre().equalsIgnoreCase(valor)) {
                cboDistrito.setSelectedIndex(i);
                return;
            }
        }
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        new frmDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    public void modoRegistroNuevo() {
        chkEstado.setSelected(true);
        chkEstado.setEnabled(false);
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // 1️⃣ Capturar datos del formulario
        String nombre = txtNombres.getText().trim();
        String apellido = txtApellidos.getText().trim();
        String correo = txtEmail.getText().trim();
        String telefono = txtTelefono.getText().trim();

        // 🔹 Obtener distrito seleccionado
        Distrito distritoSeleccionado = (Distrito) cboDistrito.getSelectedItem();
        int idDistrito = distritoSeleccionado != null ? distritoSeleccionado.getIdDistrito() : 0;
        boolean estado = chkEstado.isSelected();

        // 🔹 Validar campos obligatorios
        if (nombre.isEmpty() || apellido.isEmpty() || correo.isEmpty()
                || telefono.isEmpty() || idDistrito == 0) {
            JOptionPane.showMessageDialog(this, "⚠️ Todos los campos son obligatorios.");
            return;
        }

        // 🔹 Validar correo
        if (!correo.matches("^[\\w.-]+@[\\w.-]+\\.[A-Za-z]{2,6}$")) {
            JOptionPane.showMessageDialog(this,
                    "⚠️ El correo ingresado no tiene un formato válido. Debe contener '@' y un dominio.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 🔹 Validar teléfono EXACTAMENTE 9 dígitos y que no inicie con 0
        if (!telefono.matches("^[1-9][0-9]{8}$")) {
            JOptionPane.showMessageDialog(this,
                    "⚠️ El teléfono debe tener 9 dígitos y no empezar con 0.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        // 3️⃣ Crear objeto Cliente
        Cliente c = new Cliente(0, "----Seleccione Cliente----");
        c.setNombre(nombre);
        c.setApellido(apellido);
        c.setCorreo(correo);
        c.setTelefono(telefono);
        c.setDistrito(String.valueOf(idDistrito)); // si tu clase usa String
        c.setEstado(chkEstado.isSelected());

        // 4️⃣ Llamar al controlador
        clienteController controlador = new clienteController();
        boolean exito;
        // 5️⃣ Verificar resultado
        if (modoEdicion) {
            // Modo edición
            c.setId(idClienteEditar);
            exito = controlador.actualizarCliente(c);
        } else {
            // Modo registro
            exito = controlador.registrarCliente(c);
        }

        // 4️⃣ Obtener mensaje y tipo desde el controlador
        String msj = controlador.getMensaje();
        int tipo = controlador.getTipoMensaje();

        // 5️⃣ Mostrar resultado según tipo
        switch (tipo) {
            case 0: // ERROR
                JOptionPane.showMessageDialog(this, msj, "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case 1: // ADVERTENCIA
                JOptionPane.showMessageDialog(this, msj, "Advertencia", JOptionPane.WARNING_MESSAGE);
                break;
            case 2: // ÉXITO
                JOptionPane.showMessageDialog(this, msj, "Éxito", JOptionPane.INFORMATION_MESSAGE);
                if (!modoEdicion) {
                    Limpiar(); // Limpiar solo registro
                }
                if (modoEdicion) {
                    dispose();  // Cerrar ventana edición
                }
                break;

            default:
                JOptionPane.showMessageDialog(this, "Tipo de mensaje desconocido: " + msj, "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void Ocultar() {
        // 🔹 Ocultar label y campo de código
        lblCodigo.setVisible(false);
        txtCodigo.setVisible(false);
        txtDistrito.setVisible(false);
        // 🔹 Bloquear (por si lo muestras luego)
        txtDistrito.setEditable(false);
    }

    public void cargarDatosParaEditar(Cliente c) {
        if (c == null) {
            JOptionPane.showMessageDialog(this, "⚠️ No se han recibido datos para editar.");
            return;
        }

        this.modoEdicion = true;
        this.idClienteEditar = c.getId();
        this.setTitle("Editar Cliente");
        txtCodigo.setText(String.valueOf(c.getId()));
        txtNombres.setText(c.getNombre());
        txtApellidos.setText(c.getApellido());
        txtEmail.setText(c.getCorreo());
        txtTelefono.setText(c.getTelefono());

        // Guardar el ID del distrito en el campo oculto
        txtDistrito.setText(c.getDistrito());

        // ✅ Reflejar el estado booleano
        chkEstado.setSelected(c.isEstado());

        // 🔹 Controlar edición según rol
        if (usuarioActual instanceof Administrador) {
            Administrador admin = (Administrador) usuarioActual;

            // Todos pueden editar nombres/apellidos
            txtNombres.setEnabled(true);
            txtApellidos.setEnabled(true);
            txtEmail.setEnabled(true);
            txtTelefono.setEnabled(true);
            // El estado solo Administrador Completo puede cambiar
            chkEstado.setEnabled(admin.getTipo() == Administrador.Tipo.Completo);

        } else if ("Recepcionista".equalsIgnoreCase(usuarioActual.getRol())) {
            // Recepcionista puede editar algunos campos, pero no el estado
            txtNombres.setEnabled(true);
            txtApellidos.setEnabled(true);
            txtEmail.setEnabled(true);
            txtTelefono.setEnabled(true);
            chkEstado.setEnabled(false);
        } else {
            // Otros usuarios no pueden editar nada
            txtNombres.setEnabled(false);
            txtApellidos.setEnabled(false);
            txtEmail.setEnabled(false);
            txtTelefono.setEnabled(false);
            chkEstado.setEnabled(false);
        }

        // ✅ Seleccionar distrito en combo (por nombre o ID)
        SwingUtilities.invokeLater(() -> {
            seleccionarDistrito(c.getDistrito());
        });
        btnGuardar.setText("ACTUALIZAR");
    }

    private void btnVolverDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverDashboardActionPerformed
        // Obtener el desktopPane del formulario padre
        JDesktopPane desktopPane = this.getDesktopPane();
        if (desktopPane == null) {
            System.err.println("⚠️ No se pudo acceder al desktopPane del padre.");
            return;
        }

        frmDashboard dasbboardForm = null;

        // Recorremos los frames existentes
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            if (frame instanceof frmNuevoUsuario) { // verificar la clase correcta
                dasbboardForm = (frmDashboard) frame;
                break;
            }
        }

        // Si ya existe, traerlo al frente
        if (dasbboardForm != null) {
            try {
                dasbboardForm.setIcon(false); // si estaba minimizado
                dasbboardForm.setSelected(true);
                dasbboardForm.toFront();
            } catch (PropertyVetoException e) {
                e.printStackTrace();
            }
        } else {
            // Si no existe, crear nueva instancia y agregar al desktopPane
            dasbboardForm = new frmDashboard();
            desktopPane.add(dasbboardForm);
            dasbboardForm.setVisible(true);
        }
    }//GEN-LAST:event_btnVolverDashboardActionPerformed

    private void cboDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDistritoActionPerformed
        Distrito distrito = (Distrito) cboDistrito.getSelectedItem();
        if (distrito != null) {
            txtDistrito.setText(String.valueOf(distrito.getIdDistrito())); // guarda el ID (int → texto)
        }
    }//GEN-LAST:event_cboDistritoActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();

        // 1️⃣ Solo permitir números
        if (!Character.isDigit(c)) {
            evt.consume();
            return;
        }

        // 2️⃣ Limitar a EXACTAMENTE 9 dígitos (máximo 9)
        if (txtTelefono.getText().length() >= 9) {
            evt.consume();
            return;
        }

        // 3️⃣ No permitir que empiece con 0
        if (txtTelefono.getText().isEmpty() && c == '0') {
            evt.consume();
            return;
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNuevoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolverDashboard;
    private javax.swing.JComboBox<Distrito> cboDistrito;
    private javax.swing.JCheckBox chkEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
