package vistas;

import clases.Area;
import clases.DashboardCitasPorDia;
import clases.Servicio;
import clases.Trabajador;
import controlador.areaController;
import controlador.dashboardController;
import controlador.reporteController;
import controlador.servicioController;
import controlador.trabajadorController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.beans.PropertyVetoException;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.WeekFields;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import vistas.frmDashboard;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;
import util.Iconos;

/**
 *
 * @author v1ct0
 */
public class frmReportes extends JInternalFrame {

    /**
     * Creates new form ReportesForm
     */
    public frmReportes() {
        initComponents();
        Iconos();
        crearTablaReportes();
        cargarCombos();

        // Tamaño y centrado
        this.setSize(950, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setClosable(true);      // Mostrar botón de cerrar
        setIconifiable(false);  // Ocultar minimizar
        setMaximizable(false);  // Ocultar maximizar
        setResizable(false);    // Desactivar redimensionar
        this.setTitle("Reportes");

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboArea = new javax.swing.JComboBox<>();
        cboServicio = new javax.swing.JComboBox<>();
        cboTrabajador = new javax.swing.JComboBox<>();
        btnAplicarFiltros = new javax.swing.JButton();
        pnlGrafico = new javax.swing.JPanel();
        btnGenerar = new javax.swing.JButton();
        btnVolverDashboard = new javax.swing.JButton();
        dtFechaInicio = new com.toedter.calendar.JDateChooser();
        dtFechaFin = new com.toedter.calendar.JDateChooser();
        cboTipo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReportes = new javax.swing.JTable();
        lblReporte = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Reportes de Citas");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Fechas:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("----");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Area/Servicio :");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Trabajador:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Tipo");

        cboArea.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboAreaItemStateChanged(evt);
            }
        });
        cboArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAreaActionPerformed(evt);
            }
        });

        cboServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboServicioActionPerformed(evt);
            }
        });

        cboTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTrabajadorActionPerformed(evt);
            }
        });

        btnAplicarFiltros.setBackground(new java.awt.Color(33, 150, 243));
        btnAplicarFiltros.setForeground(new java.awt.Color(255, 255, 255));
        btnAplicarFiltros.setText("Aplicar Filtros");
        btnAplicarFiltros.setFocusPainted(false);
        btnAplicarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarFiltrosActionPerformed(evt);
            }
        });

        pnlGrafico.setBackground(new java.awt.Color(144, 202, 249));
        pnlGrafico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlGrafico.setToolTipText("");
        pnlGrafico.setMinimumSize(new java.awt.Dimension(400, 250));
        pnlGrafico.setName(""); // NOI18N
        pnlGrafico.setPreferredSize(new java.awt.Dimension(600, 300));
        pnlGrafico.setLayout(new java.awt.BorderLayout());

        btnGenerar.setBackground(new java.awt.Color(25, 118, 210));
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnVolverDashboard.setBackground(new java.awt.Color(240, 240, 240));
        btnVolverDashboard.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVolverDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datos.png"))); // NOI18N
        btnVolverDashboard.setText("Dashboard");
        btnVolverDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverDashboardActionPerformed(evt);
            }
        });

        dtFechaInicio.setDateFormatString("yyyy-MM-dd");

        dtFechaFin.setDateFormatString("yyyy-MM-dd");

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------------------Seleccionar-------------------------", "Servicios Agendados por Fecha", "Detalle de Ingresos por Servicio", "Detalle de Citas por Turno", "Indicadores de Distribuciones de citas  por dia Semanal", "Indicadores de Distribuciones de citas  por dia Mensual", "Citas Anuladas", "Agenda de Horario Citas de Trabajador", "Maximo/minimo/Promedio de Precios", " ", " ", " " }));
        cboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoActionPerformed(evt);
            }
        });

        tblReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblReportes);

        lblReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte-de-negocios.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolverDashboard)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cboTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(dtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(208, 208, 208)
                                                .addComponent(btnAplicarFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane2)
                            .addComponent(pnlGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblReporte)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnVolverDashboard))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAplicarFiltros)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10))))
                    .addComponent(jLabel3)
                    .addComponent(dtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGenerar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private final reporteController controlador = new reporteController();
    private int idTrabajadorSeleccionado = 0; // valor inicial

    private Integer idAreaSeleccionada = null;
    private Integer idServicioSeleccionado = null;

    private boolean comboTrabajadorCargando = true; // evita disparos iniciales

    private void Iconos() {
        // Asignar iconos  
        btnGenerar.setIcon(Iconos.get("reporte.png"));
        lblReporte.setIcon(Iconos.get("reporte-de-negocios.png"));
        btnVolverDashboard.setIcon(Iconos.get("datos.png"));
    }

    // 🗓️ Cargar combos al iniciar el formulario
    private void cargarCombos() {
        trabajadorController trabajadorCtrl = new trabajadorController();
        areaController areaCtrl = new areaController();

        // --- ÁREA ---
        cboArea.removeAllItems();
        cboArea.addItem(new Area(0, "----Seleccione un área----"));
        for (Area a : areaCtrl.obtenerAreas()) {
            cboArea.addItem(a);
        }
        // --- SERVICIO ---
        cboServicio.removeAllItems();
        cboServicio.addItem(new Servicio(0, "----Seleccione un servicio----"));

        // --- TRABAJADOR ---
        cboTrabajador.removeAllItems();
        cboTrabajador.addItem(new Trabajador(0, "----Seleccione Trabajador----"));
        for (Trabajador t : trabajadorCtrl.listarTrabajadores()) {
            cboTrabajador.addItem(t);
        }
        comboTrabajadorCargando = false;
    }

    private void cargarAreas() {
        areaController controller = new areaController();
        List<Area> lista = controller.obtenerAreas();

        cboArea.removeAllItems();
        cboArea.addItem(new Area(0, "----Seleccione un área----"));
        for (Area a : lista) {
            cboArea.addItem(a);
        }

        // Al iniciar, también mostrar solo el texto por defecto en servicios
        cboServicio.removeAllItems();
        cboServicio.addItem(new Servicio(0, "----Seleccione un servicio----"));
    }

    private void cargarServiciosPorArea(int idArea) {
        servicioController controller = new servicioController();
        List<Servicio> lista = controller.listarPorArea(idArea);

        cboServicio.removeAllItems();
        cboServicio.addItem(new Servicio(0, "----Seleccione un servicio----"));
        for (Servicio s : lista) {
            cboServicio.addItem(s);
        }
    }

    private void seleccionarItem(JComboBox combo, int id) {
        for (int i = 0; i < combo.getItemCount(); i++) {
            Object obj = combo.getItemAt(i);

            if (obj instanceof Trabajador && ((Trabajador) obj).getId() == id) {
                combo.setSelectedIndex(i);
                break;
            } else if (obj instanceof Servicio && ((Servicio) obj).getIdServicio() == id) {
                combo.setSelectedIndex(i);
                break;
            } else if (obj instanceof Area && ((Area) obj).getIdArea() == id) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }

    private void crearTablaReportes() {
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Día"); // 0 (oculto)
        tb.addColumn("Fecha");
        tb.addColumn("Total");
        tb.addColumn("Canceladas");
        tb.addColumn("Completadas");

        tblReportes.setModel(tb);

        // 🔒 Bloquear encabezado (no mover ni redimensionar)
        tblReportes.getTableHeader().setReorderingAllowed(false);
        tblReportes.getTableHeader().setResizingAllowed(false);

        // 🔒 Evitar edición directa
        tblReportes.setDefaultEditor(Object.class, null);

        // ❌ Ocultar primera columna “Día”
        tblReportes.getColumnModel().getColumn(0).setMinWidth(0);
        tblReportes.getColumnModel().getColumn(0).setMaxWidth(0);
        tblReportes.getColumnModel().getColumn(0).setWidth(0);

        // Ajustar altura de filas
        tblReportes.setRowHeight(25);

        // Hacer que el campo del JDateChooser no se pueda escribir manualmente
        ((JTextField) dtFechaInicio.getDateEditor().getUiComponent()).setEditable(false);
        ((JTextField) dtFechaFin.getDateEditor().getUiComponent()).setEditable(false);

        // Aplicar tamaños y alineaciones
        tamañoTablaCitas();
        alinearColumnasCitas();
    }

    private void tamañoTablaCitas() {
        if (tblReportes.getColumnCount() < 5) {
            System.out.println("❌ Error: la tabla no tiene suficientes columnas para ajustar el tamaño.");
            return;
        }

        tblReportes.getColumnModel().getColumn(1).setPreferredWidth(80);  // Fecha
        tblReportes.getColumnModel().getColumn(2).setPreferredWidth(50);  // Total
        tblReportes.getColumnModel().getColumn(3).setPreferredWidth(60);  // Canceladas
        tblReportes.getColumnModel().getColumn(4).setPreferredWidth(60);  // Completadas
    }

    private void alinearColumnasCitas() {
        DefaultTableCellRenderer izquierda = new DefaultTableCellRenderer();
        izquierda.setHorizontalAlignment(SwingConstants.LEFT);

        // Alinear según el tipo de dato
        tblReportes.getColumnModel().getColumn(1).setCellRenderer(izquierda); // Fecha
        tblReportes.getColumnModel().getColumn(2).setCellRenderer(izquierda); // Total
        tblReportes.getColumnModel().getColumn(3).setCellRenderer(izquierda); // Canceladas
        tblReportes.getColumnModel().getColumn(4).setCellRenderer(izquierda); // Completadas
    }

    private void cboTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTrabajadorActionPerformed
        if (comboTrabajadorCargando) {
            return;
        }
        Trabajador trabajadorSeleccionado = (Trabajador) cboTrabajador.getSelectedItem();

        if (trabajadorSeleccionado == null || trabajadorSeleccionado.getId() == 0) {
            idTrabajadorSeleccionado = 0; // o null si tu SP lo acepta
        } else {
            idTrabajadorSeleccionado = trabajadorSeleccionado.getId();
        }
    }//GEN-LAST:event_cboTrabajadorActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        try {
            int tipo = cboTipo.getSelectedIndex();

            if (tipo <= 0) {
                JOptionPane.showMessageDialog(this, "Seleccione un tipo de reporte.");
                return;
            }

            java.util.Date f1 = dtFechaInicio.getDate();
            java.util.Date f2 = dtFechaFin.getDate();

            // Validación de fechas solo si el reporte lo requiere
            if ((tipo == 1 || tipo == 2) && (f1 == null || f2 == null)) {
                JOptionPane.showMessageDialog(this, "Seleccione Fecha Inicio y Fecha Fin.");
                return;
            }

            // Validar que inicio ≤ fin
            if (f1 != null && f2 != null && f1.after(f2)) {
                JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser mayor que la fecha final.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validar selección de trabajador solo para el reporte de tipo 7
            if (tipo == 7 && idTrabajadorSeleccionado == 0) {
                JOptionPane.showMessageDialog(this, "Seleccione un trabajador para generar el reporte.");
                return;
            }
            // Llamada al controller
            controlador.generarReporte(tipo, f1, f2, idTrabajadorSeleccionado, idAreaSeleccionada, idServicioSeleccionado);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnVolverDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverDashboardActionPerformed
        // Obtener el desktopPane del formulario padre
        JDesktopPane desktopPane = this.getDesktopPane();
        if (desktopPane == null) {
            System.err.println("⚠️ No se pudo acceder al desktopPane del padre.");
            return;
        }

        frmDashboard dasbboardForm = null;

        // Recorremos los frames existentes
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            if (frame instanceof frmNuevoUsuario) { // verificar la clase correcta
                dasbboardForm = (frmDashboard) frame;
                break;
            }
        }

        // Si ya existe, traerlo al frente
        if (dasbboardForm != null) {
            try {
                dasbboardForm.setIcon(false); // si estaba minimizado
                dasbboardForm.setSelected(true);
                dasbboardForm.toFront();
            } catch (PropertyVetoException e) {
                e.printStackTrace();
            }
        } else {
            // Si no existe, crear nueva instancia y agregar al desktopPane
            dasbboardForm = new frmDashboard();
            desktopPane.add(dasbboardForm);
            dasbboardForm.setVisible(true);
        }
    }//GEN-LAST:event_btnVolverDashboardActionPerformed

    private void cargarTablaCita() {
        try {
            if (dtFechaInicio.getDate() == null || dtFechaFin.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Seleccione ambas fechas para filtrar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            LocalDate fechaInicio = dtFechaInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaFin = dtFechaFin.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            if (fechaInicio.isAfter(fechaFin)) {
                JOptionPane.showMessageDialog(this, "La fecha inicial no puede ser mayor que la final.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Cargar tabla y gráfico según las fechas seleccionadas
            cargarTablaCitasPorDia(fechaInicio, fechaFin);
            cargarGraficoCitasPorDia(fechaInicio, fechaFin);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarTablaCitasPorDia(LocalDate inicio, LocalDate fin) {
        dashboardController controller = new dashboardController();
        List<DashboardCitasPorDia> lista = controller.obtenerCitasPorDia(inicio, fin);

        // Modelo no editable
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // ❌ No permite editar celdas
            }
        };

        model.addColumn("Día");
        model.addColumn("Fecha");
        model.addColumn("Total");
        model.addColumn("Canceladas");
        model.addColumn("Completadas");

        for (DashboardCitasPorDia d : lista) {
            model.addRow(new Object[]{
                traducirDia(d.getDiaSemana()),
                d.getFecha(),
                d.getTotalCitas(),
                d.getCitasCanceladas(),
                d.getCitasCompletadas()
            });
        }
        // Asignar modelo a la tabla
        tblReportes.setModel(model);

        // ❌ Ocultar primera columna ("Día")
        tblReportes.getColumnModel().getColumn(0).setMinWidth(0);
        tblReportes.getColumnModel().getColumn(0).setMaxWidth(0);
        tblReportes.getColumnModel().getColumn(0).setWidth(0);

        // 🔧 Ajustes visuales
        tblReportes.setRowHeight(25);
        tblReportes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // 🧩 Alinear y ajustar tamaño
        tamañoTablaCitas();
        alinearColumnasCitas();
    }

    private void cargarGraficoCitasPorDia(LocalDate fechaInicio, LocalDate fechaFin) {
        try {
            dashboardController controller = new dashboardController();

            List<DashboardCitasPorDia> lista = controller.obtenerCitasPorDia(fechaInicio, fechaFin);

            if (lista == null || lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay citas en el rango seleccionado.", "Información", JOptionPane.INFORMATION_MESSAGE);
                pnlGrafico.removeAll();
                pnlGrafico.revalidate();
                pnlGrafico.repaint();
                return;
            }

            // Crear dataset
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            for (DashboardCitasPorDia d : lista) {
                dataset.addValue(d.getTotalCitas(), "Citas", traducirDia(d.getDiaSemana()));
            }

            // Crear gráfico de barras horizontal
            JFreeChart chart = ChartFactory.createBarChart(
                    "Citas por Día de la Semana", // título
                    "Día", // eje X
                    "Cantidad de Citas", // eje Y
                    dataset,
                    PlotOrientation.HORIZONTAL, // orientación horizontal
                    false, true, false
            );

            // Personalización visual
            chart.setBackgroundPaint(Color.WHITE);
            chart.getTitle().setPaint(new Color(0, 102, 204));

            CategoryPlot plot = chart.getCategoryPlot();
            plot.setBackgroundPaint(Color.WHITE);
            plot.setDomainGridlinePaint(Color.LIGHT_GRAY);
            plot.setRangeGridlinePaint(Color.LIGHT_GRAY);

            // 🧩 Control de grosor de barras y separación
            BarRenderer renderer = (BarRenderer) plot.getRenderer();
            renderer.setSeriesPaint(0, new Color(255, 102, 102)); // color suave
            renderer.setBarPainter(new StandardBarPainter());     // barras planas (sin gradiente)
            renderer.setMaximumBarWidth(0.2);                     // evita que las barras se adelgacen demasiado
            renderer.setItemMargin(0.1);                          // separación entre grupos
            plot.getDomainAxis().setCategoryMargin(0.2);          // margen entre categorías

            // Configurar el ChartPanel
            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setMouseWheelEnabled(false);   // No permitir zoom
            chartPanel.setDomainZoomable(false);      // No permitir zoom en eje X
            chartPanel.setRangeZoomable(false);       // No permitir zoom en eje Y
            chartPanel.setPopupMenu(null);            // Quitar menú contextual
            chartPanel.setDisplayToolTips(false);     // Sin tooltips

            // Que se adapte automáticamente al tamaño del panel contenedor
            chartPanel.setPreferredSize(null);
            chartPanel.setMaximumDrawWidth(Integer.MAX_VALUE);
            chartPanel.setMaximumDrawHeight(Integer.MAX_VALUE);
            chartPanel.setMinimumDrawWidth(0);
            chartPanel.setMinimumDrawHeight(0);

            // Centrar el gráfico horizontalmente dentro del panel
            pnlGrafico.removeAll();
            pnlGrafico.setLayout(new BorderLayout());
            pnlGrafico.add(chartPanel, BorderLayout.CENTER);
            pnlGrafico.revalidate();
            pnlGrafico.repaint();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar el gráfico: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void btnAplicarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarFiltrosActionPerformed
        if (dtFechaInicio.getDate() == null || dtFechaFin.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione ambas fechas para filtrar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        LocalDate fechaInicio = dtFechaInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate fechaFin = dtFechaFin.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        if (fechaInicio.isAfter(fechaFin)) {
            JOptionPane.showMessageDialog(this, "La fecha inicial no puede ser mayor que la final.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Validar si ambas fechas están en la misma semana
        WeekFields weekFields = WeekFields.of(DayOfWeek.MONDAY, 1); // Semana inicia lunes
        int semanaInicio = fechaInicio.get(weekFields.weekOfWeekBasedYear());
        int semanaFin = fechaFin.get(weekFields.weekOfWeekBasedYear());

        if (semanaInicio != semanaFin) {
            JOptionPane.showMessageDialog(this,
                    "El rango seleccionado no corresponde a una sola semana.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Si pasa la validación, cargar tabla normalmente
        cargarTablaCita();
    }//GEN-LAST:event_btnAplicarFiltrosActionPerformed

    private void cboAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAreaActionPerformed

        Area area = (Area) cboArea.getSelectedItem();

        if (area == null || area.getIdArea() == 0) {
            idAreaSeleccionada = null; // todas las áreas
            // Limpiar combo de servicios
            cboServicio.removeAllItems();
            cboServicio.addItem(new Servicio(0, "----Seleccione un servicio----"));
            idServicioSeleccionado = null; // ningún servicio seleccionado
        } else {
            idAreaSeleccionada = area.getIdArea();
            cargarServiciosPorArea(idAreaSeleccionada); // llenar servicios del área
        }
    }//GEN-LAST:event_cboAreaActionPerformed

    private void cboAreaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboAreaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Area areaSeleccionada = (Area) cboArea.getSelectedItem();
            if (areaSeleccionada != null && areaSeleccionada.getIdArea() > 0) {
                cargarServiciosPorArea(areaSeleccionada.getIdArea());
            } else {
                // Si vuelve al valor por defecto
                cboServicio.removeAllItems();
                cboServicio.addItem(new Servicio(0, "----Seleccione un servicio----"));
            }
        }
    }//GEN-LAST:event_cboAreaItemStateChanged

    private void cboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoActionPerformed


    }//GEN-LAST:event_cboTipoActionPerformed

    private void cboServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboServicioActionPerformed
        Servicio servicio = (Servicio) cboServicio.getSelectedItem();

        if (servicio == null || servicio.getIdServicio() == 0) {
            idServicioSeleccionado = null; // todos los servicios
        } else {
            idServicioSeleccionado = servicio.getIdServicio();
        }
    }//GEN-LAST:event_cboServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarFiltros;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnVolverDashboard;
    private javax.swing.JComboBox<Area> cboArea;
    private javax.swing.JComboBox<Servicio> cboServicio;
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JComboBox<Trabajador> cboTrabajador;
    private com.toedter.calendar.JDateChooser dtFechaFin;
    private com.toedter.calendar.JDateChooser dtFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblReporte;
    private javax.swing.JPanel pnlGrafico;
    private javax.swing.JTable tblReportes;
    // End of variables declaration//GEN-END:variables

    private String traducirDia(String diaSemana) {
        if (diaSemana == null) {
            return "";
        }

        switch (diaSemana.toLowerCase()) {
            case "monday":
                return "Lunes";
            case "tuesday":
                return "Martes";
            case "wednesday":
                return "Miércoles";
            case "thursday":
                return "Jueves";
            case "friday":
                return "Viernes";
            case "saturday":
                return "Sábado";
            case "sunday":
                return "Domingo";
            default:
                return diaSemana; // En caso de que ya venga en español o distinto
        }
    }

}
