package vistas;

import clases.Servicio;
import clases.SesionUsuario;
import clases.Usuario;
import clasesDAO.servicioDAO;
import controlador.areaController;
import controlador.servicioController;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import recursos.ButtonPanelCellAreaServicio;
import util.Iconos;

/**
 *
 * @author Administrador
 */
public class frmServicio extends JInternalFrame {

    /**
     * Creates new form frmServicio
     */
    public frmServicio() {
        initComponents();
        Iconos();
        crearTablaAreasServicios();
        Limpiar();
        this.setSize(950, 600);
        // Configuración correcta para JInternalFrame
        this.setClosable(true);
        this.setIconifiable(false);
        this.setMaximizable(false);
        this.setResizable(false);
        this.setTitle("Gestión de Servicio");
        this.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);

        LimpiarAviso();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        lblAviso = new javax.swing.JLabel();
        btnNuevoServicio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicio = new javax.swing.JTable();
        btnBuscarServicio = new javax.swing.JButton();
        btnVolverDashboard = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        txtServicio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Gestion de Servicio");

        btnMostrar.setBackground(new java.awt.Color(0, 0, 0));
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mostrar.png"))); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        lblAviso.setText("jLabel5");

        btnNuevoServicio.setBackground(new java.awt.Color(76, 175, 80));
        btnNuevoServicio.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cita.png"))); // NOI18N
        btnNuevoServicio.setText("+ Nuevo Servicio");
        btnNuevoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoServicioActionPerformed(evt);
            }
        });

        tblServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblServicio);

        btnBuscarServicio.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscarServicio.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscarServicio.setText("Buscar");
        btnBuscarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarServicioActionPerformed(evt);
            }
        });

        btnVolverDashboard.setBackground(new java.awt.Color(240, 240, 240));
        btnVolverDashboard.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVolverDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datos.png"))); // NOI18N
        btnVolverDashboard.setText("Dashboard");
        btnVolverDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverDashboardActionPerformed(evt);
            }
        });

        lblCodigo.setText("Codigo:");

        jLabel2.setText("Area:");

        jLabel3.setText("Servicio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(282, 282, 282))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevoServicio))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCodigo)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigo)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnVolverDashboard))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(lblAviso)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnVolverDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnMostrar)
                        .addGap(39, 39, 39)
                        .addComponent(lblAviso))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(btnNuevoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Iconos() {
        // Asignar iconos  
        btnNuevoServicio.setIcon(Iconos.get("cita.png"));
        btnMostrar.setIcon(Iconos.get("mostrar.png"));
        btnBuscarServicio.setIcon(Iconos.get("buscar.png"));
        btnVolverDashboard.setIcon(Iconos.get("datos.png"));
    }
    private void LimpiarAviso() {
        lblAviso.setVisible(false);
    }

    private void Limpiar() {
        txtCodigo.setText("");
        txtArea.setText("");
        txtServicio.setText("");
    }

    public void crearTablaAreasServicios() {
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Cod Área");
        tb.addColumn("Área");
        tb.addColumn("Cod Servicio");
        tb.addColumn("Servicio");
        tb.addColumn("Precio");
        tb.addColumn("Duración (min)");
        tb.addColumn("Acciones");

        tblServicio.setModel(tb);

        tblServicio.getColumnModel().getColumn(6).setCellRenderer(new ButtonPanelCellAreaServicio(tblServicio));
        tblServicio.getColumnModel().getColumn(6).setCellEditor(new ButtonPanelCellAreaServicio(tblServicio));

        // Bloquear movimiento y redimensionamiento
        tblServicio.getTableHeader().setReorderingAllowed(false);
        tblServicio.getTableHeader().setResizingAllowed(false);

        // No permitir editar celdas
        tblServicio.setDefaultEditor(Object.class, null);

        // Ocultar columnas internas si quieres (ejemplo: cod área y servicio)
        tblServicio.getColumnModel().getColumn(0).setMinWidth(0);
        tblServicio.getColumnModel().getColumn(0).setMaxWidth(0);
        tblServicio.getColumnModel().getColumn(0).setWidth(0);

        tblServicio.getColumnModel().getColumn(2).setMinWidth(2);
        tblServicio.getColumnModel().getColumn(2).setMaxWidth(2);
        tblServicio.getColumnModel().getColumn(2).setWidth(2);

        tamañoTablaAreasServicios();
    }

    public void tamañoTablaAreasServicios() {
        if (tblServicio.getColumnCount() < 6) {
            System.out.println("❌ No hay columnas suficientes.");
            return;
        }
        // Ajustar anchos
        tblServicio.getColumnModel().getColumn(1).setPreferredWidth(110); // Área
        tblServicio.getColumnModel().getColumn(3).setPreferredWidth(150); // Servicio
        tblServicio.getColumnModel().getColumn(4).setPreferredWidth(20);  // Precio
        tblServicio.getColumnModel().getColumn(5).setPreferredWidth(20);  // Duración

        // Bloquear movimiento y redimensionamiento
        tblServicio.getTableHeader().setReorderingAllowed(false);
        tblServicio.getTableHeader().setResizingAllowed(false);

        // 👉 CENTRAR Precio (columna 4) y Duración (columna 5)
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tblServicio.getColumnModel().getColumn(4).setCellRenderer(centerRenderer); // Precio
        tblServicio.getColumnModel().getColumn(5).setCellRenderer(centerRenderer); // Duración

        // 👉 AUMENTAR ALTO DE FILA PARA QUE LOS BOTONES NO ESTÉN PEGADOS
        tblServicio.setRowHeight(25);  // Puedes usar 34 si quieres más espacio
    }

    public void cargarTablaServicios() {
        DefaultTableModel modelo = (DefaultTableModel) tblServicio.getModel();
        modelo.setRowCount(0); // limpiar tabla

        areaController ctrl = new areaController();
        ArrayList<Servicio> lista = ctrl.listar();

        for (Servicio s : lista) {
            modelo.addRow(new Object[]{
                s.getArea().getIdArea(), // Id del área
                s.getArea().getNombreArea(), // Nombre del área
                s.getIdServicio(), // Id del servicio
                s.getNombre(), // Nombre del servicio
                s.getPrecio(), // Precio
                s.getDuracion(), // Duración
                "Editar / Eliminar" // Acciones
            });
        }
    }


    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        try {
            cargarTablaServicios();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "❌ Error al mostrar servicios: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnNuevoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoServicioActionPerformed
        // Obtener usuario logueado
        Usuario usr = SesionUsuario.getUsuarioActual();

        if (usr == null) {
            JOptionPane.showMessageDialog(null, "🚫 No hay usuario activo.", "Acceso denegado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar rol: Administrador Limitado no puede registrar clientes
        if ("Administrador Limitado".equalsIgnoreCase(usr.getRol())) {
            JOptionPane.showMessageDialog(null,
                    "🚫 No tienes permiso para Registrar Cita.",
                    "Acceso denegado", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JDesktopPane desktopPane = this.getDesktopPane();
        if (desktopPane == null) {
            return;
        }

        frmNuevoServicio servicioForm = null;
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            if (frame instanceof frmNuevaCita) {
                servicioForm = (frmNuevoServicio) frame;
                break;
            }
        }

        if (servicioForm != null) {
            try {
                servicioForm.setIcon(false);
                servicioForm.setSelected(true);
                servicioForm.toFront();
                //servicioForm.habilitarCampos(); // habilita modo registro
                //servicioForm.configurarEstadoPendiente(); // 🔹 Aquí fijamos el estado
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            servicioForm = new frmNuevoServicio();
            desktopPane.add(servicioForm);
            servicioForm.setVisible(true);
            //servicioForm.habilitarCampos(); // ✅ Habilitar los campos al abrir por primera vez
            //servicioForm.configurarEstadoPendiente(); // 🔹 Fijar estado al abrir
        }
    }//GEN-LAST:event_btnNuevoServicioActionPerformed

    private void btnBuscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarServicioActionPerformed
        servicioController ctrl = new servicioController();
        String criterio = "";

        // Resetear colores de campos
        txtCodigo.setBackground(Color.white);
        txtArea.setBackground(Color.white);
        txtServicio.setBackground(Color.white);

        // 🔹 Prioridad: busca por código o nombre
        if (!txtCodigo.getText().trim().isEmpty()) {
            criterio = txtCodigo.getText().trim();
        } else if (!txtArea.getText().trim().isEmpty()) {
            criterio = txtArea.getText().trim();
        } else if (!txtServicio.getText().trim().isEmpty()) {
            criterio = txtServicio.getText().trim();
        }
        if (criterio.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese código o nombre para buscar", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // Limpiar tabla
        DefaultTableModel tb = (DefaultTableModel) tblServicio.getModel();
        tb.setRowCount(0);

        // Buscar usando el controller
        ArrayList<Servicio> lista = ctrl.buscar(criterio);

        if (!lista.isEmpty()) {
            for (Servicio s : lista) {
                Object[] fila = {
                    s.getArea().getIdArea(),
                    s.getArea().getNombreArea(),
                    s.getIdServicio(),
                    s.getNombre(),
                    s.getPrecio(),
                    s.getDuracion(),
                    "Editar / Eliminar"
                };
                tb.addRow(fila);
            }

            JOptionPane.showMessageDialog(null, "✅ " + lista.size() + " servicio(s) encontrado(s)", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Colorear en rojo si no encuentra
            txtCodigo.setBackground(Color.red);
            txtArea.setBackground(Color.red);
            txtServicio.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "❌ No se encontraron servicios o áreas", "Error", JOptionPane.ERROR_MESSAGE);
        }
        Limpiar();
        
        txtCodigo.setBackground(Color.white);
        txtArea.setBackground(Color.white);
        txtServicio.setBackground(Color.white);
    }//GEN-LAST:event_btnBuscarServicioActionPerformed

    private void btnVolverDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverDashboardActionPerformed

    }//GEN-LAST:event_btnVolverDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarServicio;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnNuevoServicio;
    private javax.swing.JButton btnVolverDashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTable tblServicio;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtServicio;
    // End of variables declaration//GEN-END:variables
}
