package vistas;

import clases.Trabajador;

import controlador.trabajadorController;

import java.awt.Color;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import vistas.frmDashboard;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import recursos.ButtonPanelCellTrabajador;
import util.Iconos;

/**
 *
 * @author v1ct0
 */
public class frmTrabajadores extends JInternalFrame {

    /**
     * Creates new form TrabajadoresForm
     */
    public frmTrabajadores() {
        initComponents();
        Iconos();

        crearTabla();
        tamañoTabla();
        // Tamaño y centrado
        this.setSize(950, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setClosable(true);      // ✔ botón cerrar
        this.setIconifiable(false);   // Ocultar minimizar
        this.setMaximizable(false);  // Ocultar maximizar
        this.setResizable(false);    // Desactivar redimensionar
        this.setTitle("Gestion Trabajador");

        Limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNuevoTrabajador = new javax.swing.JButton();
        btnVolverDashboard = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTrabajadores = new javax.swing.JTable();
        btnMostrar = new javax.swing.JButton();
        lblAviso = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBuscarEspecialidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtBuscarNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarApellido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Gestión de Trabajadores");

        btnNuevoTrabajador.setBackground(new java.awt.Color(76, 175, 80));
        btnNuevoTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoTrabajador.setText("+ Nuevo Trabajador");
        btnNuevoTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoTrabajadorActionPerformed(evt);
            }
        });

        btnVolverDashboard.setBackground(new java.awt.Color(240, 240, 240));
        btnVolverDashboard.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVolverDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datos.png"))); // NOI18N
        btnVolverDashboard.setText("Dashboard");
        btnVolverDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverDashboardActionPerformed(evt);
            }
        });

        tblTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblTrabajadores);

        btnMostrar.setBackground(new java.awt.Color(0, 0, 0));
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mostrar.png"))); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        lblAviso.setText("jLabel2");

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Especialidad:");

        lblCodigo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCodigo.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Apellido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBuscarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215)
                        .addComponent(btnNuevoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnVolverDashboard)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(lblAviso)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolverDashboard)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar))
                .addGap(1, 1, 1)
                .addComponent(lblAviso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)
                        .addComponent(txtBuscarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Iconos() {
        // Asignar iconos  
        btnMostrar.setIcon(Iconos.get("mostrar.png"));
        btnBuscar.setIcon(Iconos.get("buscar.png"));
        btnVolverDashboard.setIcon(Iconos.get("datos.png"));
    }

    private void Limpiar() {
        lblAviso.setVisible(false);

    }
    private void btnNuevoTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoTrabajadorActionPerformed
        // Obtener el desktopPane del formulario actual (frmTrabajadores)
        JDesktopPane desktopPane = this.getDesktopPane();
        if (desktopPane == null) {
            JOptionPane.showMessageDialog(this, "No se pudo acceder al DesktopPane principal.");
            return;
        }
        // 2️⃣ Crear instancia del nuevo formulario hijo
        frmNuevoTrabajador nuevoTrabajador = null;

        // Verificamos si ya existe un frmNuevoTrabajador abierto
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            if (frame instanceof frmNuevoTrabajador) {
                nuevoTrabajador = (frmNuevoTrabajador) frame;
                break;
            }
        }

        if (nuevoTrabajador != null) {
            // Si ya existe, lo traemos al frente
            try {
                nuevoTrabajador.setIcon(false);
                nuevoTrabajador.setSelected(true);
                nuevoTrabajador.toFront();
                nuevoTrabajador.habilitarCampos();
                nuevoTrabajador.aplicarPermisosTrabajador(); // aplica permisos según rol

            } catch (PropertyVetoException e) {
                e.printStackTrace();
            }
        } else {
            // Si no existe, creamos uno nuevo
            nuevoTrabajador = new frmNuevoTrabajador();
            desktopPane.add(nuevoTrabajador);
            nuevoTrabajador.setVisible(true);
            nuevoTrabajador.habilitarCampos(); // ✅ Nuevo formulario = campos activos
            nuevoTrabajador.aplicarPermisosTrabajador(); // aplica permisos según rol
            try {
                nuevoTrabajador.setSelected(true);
            } catch (PropertyVetoException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnNuevoTrabajadorActionPerformed

    private void btnVolverDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverDashboardActionPerformed
        // Obtener el desktopPane del formulario padre
        JDesktopPane desktopPane = this.getDesktopPane();
        if (desktopPane == null) {
            System.err.println("⚠️ No se pudo acceder al desktopPane del padre.");
            return;
        }

        frmDashboard dasbboardForm = null;

        // Recorremos los frames existentes
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            if (frame instanceof frmNuevoUsuario) { // verificar la clase correcta
                dasbboardForm = (frmDashboard) frame;
                break;
            }
        }

        // Si ya existe, traerlo al frente
        if (dasbboardForm != null) {
            try {
                dasbboardForm.setIcon(false); // si estaba minimizado
                dasbboardForm.setSelected(true);
                dasbboardForm.toFront();
            } catch (PropertyVetoException e) {
                e.printStackTrace();
            }
        } else {
            // Si no existe, crear nueva instancia y agregar al desktopPane
            dasbboardForm = new frmDashboard();
            desktopPane.add(dasbboardForm);
            dasbboardForm.setVisible(true);
        }
    }//GEN-LAST:event_btnVolverDashboardActionPerformed

    private void abrirFormularioEditar(Trabajador trabajador) {
        try {
            frmNuevoTrabajador frm = new frmNuevoTrabajador();

            // Llamar al método de carga en modo edición
            frm.cargarDatosParaEditar(trabajador);

            // Agregar el formulario al DesktopPane
            JDesktopPane desktop = getDesktopPane();
            desktop.add(frm);
            frm.setVisible(true);
            frm.setSelected(true);

        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }

    private void cargarTrabajadores() {
        trabajadorController tc = new trabajadorController(); // tu DAO que usa Store Procedure
        ArrayList<Trabajador> lista = tc.listarTrabajadores();
        int countInactivos = 0;

        DefaultTableModel tb = (DefaultTableModel) tblTrabajadores.getModel();
        tb.setRowCount(0); // Limpiar tabla

        for (Trabajador t : lista) {
            Object[] fila = {
                t.getId(),
                t.getNombres(),
                t.getApellidos(),
                t.getEspecialidad(),
                t.getHorario(),
                t.getIdArea(),
                t.isEstado() ? "Activo" : "Inactivo",
                "Acciones"
            };
            tb.addRow(fila);

            if (!t.isEstado()) {
                countInactivos++;
            }
        }

        // Configurar JTable
        tblTrabajadores.getColumn("Acciones").setCellRenderer(new ButtonPanelCellTrabajador(tblTrabajadores));
        tblTrabajadores.getColumn("Acciones").setCellEditor(new ButtonPanelCellTrabajador(tblTrabajadores));
        tblTrabajadores.setRowHeight(25);
        tblTrabajadores.setDefaultEditor(Object.class, null);
        tblTrabajadores.getColumnModel().getColumn(0).setPreferredWidth(20);

        // Mostrar aviso si hay trabajadores inactivos
        if (countInactivos > 0) {
            lblAviso.setText("Aviso: hay " + countInactivos + " trabajadores inactivos, se recomienda revisarlos");
            lblAviso.setForeground(Color.red);
            lblAviso.setVisible(true);
        } else {
            lblAviso.setVisible(false);
        }
    }

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        try {
            trabajadorController controlador = new trabajadorController();
            ArrayList<Trabajador> listaTrabajadores = controlador.listarTrabajadores();

            // Limpiar JTable antes de volver a cargar datos
            DefaultTableModel tb = (DefaultTableModel) tblTrabajadores.getModel();
            tb.setRowCount(0);

            int countInactivos = 0;

            if (listaTrabajadores != null && !listaTrabajadores.isEmpty()) {
                for (Trabajador t : listaTrabajadores) {
                    Object[] fila = {
                        t.getId(),
                        t.getNombres(),
                        t.getApellidos(),
                        t.getEspecialidad(),
                        t.getHorario(),
                        t.getCodArea(),
                        t.isEstado() ? "Activo" : "Inactivo",
                        "Acciones"
                    };
                    tb.addRow(fila);

                    if (!t.isEstado()) {
                        countInactivos++;
                    }
                }

                // 🎨 Configurar columna de acciones con botones
                tblTrabajadores.getColumn("Acciones").setCellRenderer(new ButtonPanelCellTrabajador(tblTrabajadores));
                tblTrabajadores.getColumn("Acciones").setCellEditor(new ButtonPanelCellTrabajador(tblTrabajadores));
                tblTrabajadores.setRowHeight(25);

                // Ajustar tamaño de columnas
                tamañoTabla();

                // 🔒 Bloquear edición de celdas
                tblTrabajadores.setDefaultEditor(Object.class, null);
                tblTrabajadores.getTableHeader().setReorderingAllowed(false);
                tblTrabajadores.getTableHeader().setResizingAllowed(false);

                // 🔔 Mostrar aviso si hay inactivos
                if (countInactivos > 0) {
                    lblAviso.setText("Aviso: hay " + countInactivos + " trabajadores inactivos, se recomienda revisarlos");
                    lblAviso.setForeground(Color.RED);
                    lblAviso.setVisible(true);
                } else {
                    lblAviso.setVisible(false);
                }

            } else {
                lblAviso.setText("No hay trabajadores registrados");
                lblAviso.setForeground(Color.GRAY);
                lblAviso.setVisible(true);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "❌ Error al mostrar trabajadores: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        trabajadorController ctrl = new trabajadorController();
        String criterio = "";

        // 🔹 Prioridad: si se ingresa código, usa código; si no, usa nombre
        if (!txtBuscarNombre.getText().trim().isEmpty()) {
            criterio = txtBuscarNombre.getText().trim();
        } else if (!txtBuscarApellido.getText().trim().isEmpty()) {
            criterio = txtBuscarApellido.getText().trim();
        } else if (!txtBuscarEspecialidad.getText().trim().isEmpty()) {
            criterio = txtBuscarEspecialidad.getText().trim();
        }

        if (criterio.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese nombre, apellido o especialidad para buscar");
            return;
        }

        DefaultTableModel tb = (DefaultTableModel) tblTrabajadores.getModel();
        tb.setRowCount(0);

        ArrayList<Trabajador> lista = ctrl.buscarTrabajador(criterio);

        if (!lista.isEmpty()) {
            for (Trabajador t : lista) {
                Object[] fila = {
                    t.getId(),
                    t.getNombres(),
                    t.getApellidos(),
                    t.getEspecialidad(),
                    t.getHorario(),
                    t.getCodArea(),
                    t.isEstado() ? "Activo" : "Inactivo",
                    "Acciones"
                };
                tb.addRow(fila);
            }
            JOptionPane.showMessageDialog(null, "✅ " + lista.size() + " trabajador(es) encontrado(s)", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            txtBuscarNombre.setBackground(Color.red);
            txtBuscarEspecialidad.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "❌ Trabajador no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // 🧹🔹 LIMPIAR CAMPOS DE BÚSQUEDA DESPUÉS DE BUSCAR
        txtBuscarNombre.setText("");
        txtBuscarApellido.setText("");
        txtBuscarEspecialidad.setText("");
        // Opcional: volver a color blanco
        txtBuscarNombre.setBackground(Color.white);
        txtBuscarApellido.setBackground(Color.white);
        txtBuscarEspecialidad.setBackground(Color.white);
    }//GEN-LAST:event_btnBuscarActionPerformed

    public void crearTabla() {
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Codigo"); // Se mantiene para referencia interna (oculto)
        tb.addColumn("Nombre");
        tb.addColumn("Apellido");
        tb.addColumn("Especialidad");
        tb.addColumn("Horario");
        tb.addColumn("Área");
        tb.addColumn("Estado");
        tb.addColumn("Acciones");
        tblTrabajadores.setModel(tb);

        // 🔒 Evita que el usuario mueva o redimensione las columnas
        tblTrabajadores.getTableHeader().setReorderingAllowed(false);
        tblTrabajadores.getTableHeader().setResizingAllowed(false);

        // Evitar edición directa de las celdas
        tblTrabajadores.setDefaultEditor(Object.class, null);

        // Ocultar la columna "Código" visualmente
        tblTrabajadores.getColumnModel().getColumn(0).setMinWidth(0);
        tblTrabajadores.getColumnModel().getColumn(0).setMaxWidth(0);
        tblTrabajadores.getColumnModel().getColumn(0).setWidth(0);
    }

    public void tamañoTabla() {
        if (tblTrabajadores.getColumnCount() < 7) {
            System.out.println("❌ Error: la tabla no tiene suficientes columnas para ajustar el tamaño.");
            return;
        }
        tblTrabajadores.getColumnModel().getColumn(1).setPreferredWidth(50);  // Nombre
        tblTrabajadores.getColumnModel().getColumn(2).setPreferredWidth(70);  // Apellido
        tblTrabajadores.getColumnModel().getColumn(3).setPreferredWidth(100);  // Especialidad
        tblTrabajadores.getColumnModel().getColumn(4).setPreferredWidth(20);  // Horario
        tblTrabajadores.getColumnModel().getColumn(5).setPreferredWidth(70);  // Área
        tblTrabajadores.getColumnModel().getColumn(6).setPreferredWidth(40);  // Estado

        // 🔒 Opcional: bloquear reordenamiento y redimensionamiento de columnas
        tblTrabajadores.getTableHeader().setReorderingAllowed(false);
        tblTrabajadores.getTableHeader().setResizingAllowed(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnNuevoTrabajador;
    private javax.swing.JButton btnVolverDashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTable tblTrabajadores;
    private javax.swing.JTextField txtBuscarApellido;
    private javax.swing.JTextField txtBuscarEspecialidad;
    private javax.swing.JTextField txtBuscarNombre;
    // End of variables declaration//GEN-END:variables
}
